#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../../config/environment'

country = Country.find_by_name('Brazil')
country ||= Country.create(:name => 'Brazil')

state = country.states.find_by_name('Bahia')
state ||= State.create!( :name => 'Bahia', :code => 'BA', :country => country);

c = City.new(:name => 'Abadia', :zip_code => '48.320-000', :state => state); c.save; 
c = City.new(:name => 'Abaira', :zip_code => '46.690-000', :state => state); c.save; 
c = City.new(:name => 'Abare', :zip_code => '48.680-000', :state => state); c.save; 
c = City.new(:name => 'Abobora', :zip_code => '48.912-000', :state => state); c.save; 
c = City.new(:name => 'Abrantes', :zip_code => '42.840-000', :state => state); c.save; 
c = City.new(:name => 'Acajutiba', :zip_code => '48.360-000', :state => state); c.save; 
c = City.new(:name => 'Acu Da Torre', :zip_code => '48.288-000', :state => state); c.save; 
c = City.new(:name => 'Acudina', :zip_code => '47.645-000', :state => state); c.save; 
c = City.new(:name => 'Acupe', :zip_code => '44.218-000', :state => state); c.save; 
c = City.new(:name => 'Adustina', :zip_code => '48.435-000', :state => state); c.save; 
c = City.new(:name => 'Afligidos', :zip_code => '44.338-000', :state => state); c.save; 
c = City.new(:name => 'Afranio Peixoto', :zip_code => '46.965-000', :state => state); c.save; 
c = City.new(:name => 'Agua Doce', :zip_code => '45.295-000', :state => state); c.save; 
c = City.new(:name => 'Agua Fria', :zip_code => '48.170-000', :state => state); c.save; 
c = City.new(:name => 'Erico Cardoso', :zip_code => '46.180-000', :state => state); c.save; 
c = City.new(:name => 'Aguas Do Paulista', :zip_code => '47.505-000', :state => state); c.save; 
c = City.new(:name => 'Aiquara', :zip_code => '45.220-000', :state => state); c.save; 
c = City.new(:name => 'Alagoinhas', :zip_code => '48.000-000', :state => state); c.save; 
c = City.new(:name => 'Alcobaca', :zip_code => '45.990-000', :state => state); c.save; 
c = City.new(:name => 'Algodao', :zip_code => '45.582-000', :state => state); c.save; 
c = City.new(:name => 'Algodoes', :zip_code => '48.832-000', :state => state); c.save; 
c = City.new(:name => 'Almadina', :zip_code => '45.640-000', :state => state); c.save; 
c = City.new(:name => 'Alto Bonito', :zip_code => '44.805-000', :state => state); c.save; 
c = City.new(:name => 'Amado state', :zip_code => '48.282-000', :state => state); c.save; 
c = City.new(:name => 'Amaniu', :zip_code => '47.380-000', :state => state); c.save; 
c = City.new(:name => 'Amargosa', :zip_code => '45.300-000', :state => state); c.save; 
c = City.new(:name => 'Amelia Rodrigues', :zip_code => '44.230-000', :state => state); c.save; 
c = City.new(:name => 'America Dourada', :zip_code => '44.910-000', :state => state); c.save; 
c = City.new(:name => 'Americo Alves', :zip_code => '47.370-000', :state => state); c.save; 
c = City.new(:name => 'Anage', :zip_code => '45.180-000', :state => state); c.save; 
c = City.new(:name => 'Andarai', :zip_code => '46.830-000', :state => state); c.save; 
c = City.new(:name => 'Andorinha', :zip_code => '48.990-000', :state => state); c.save; 
c = City.new(:name => 'Angical', :zip_code => '47.960-000', :state => state); c.save; 
c = City.new(:name => 'Anguera', :zip_code => '44.670-000', :state => state); c.save; 
c = City.new(:name => 'Antas', :zip_code => '48.420-000', :state => state); c.save; 
c = City.new(:name => 'Antonio Cardoso', :zip_code => '44.180-000', :state => state); c.save; 
c = City.new(:name => 'Antonio Goncalves', :zip_code => '44.780-000', :state => state); c.save; 
c = City.new(:name => 'Apora', :zip_code => '48.350-000', :state => state); c.save; 
c = City.new(:name => 'Apuarema', :zip_code => '45.355-000', :state => state); c.save; 
c = City.new(:name => 'Aracas', :zip_code => '48.108-000', :state => state); c.save; 
c = City.new(:name => 'Aracatu', :zip_code => '46.130-000', :state => state); c.save; 
c = City.new(:name => 'Araci', :zip_code => '48.760-000', :state => state); c.save; 
c = City.new(:name => 'Aramari', :zip_code => '48.130-000', :state => state); c.save; 
c = City.new(:name => 'Arapiranga', :zip_code => '46.177-000', :state => state); c.save; 
c = City.new(:name => 'Arataca', :zip_code => '45.695-000', :state => state); c.save; 
c = City.new(:name => 'Aratuipe', :zip_code => '44.490-000', :state => state); c.save; 
c = City.new(:name => 'Argoim', :zip_code => '44.525-000', :state => state); c.save; 
c = City.new(:name => 'Argolo', :zip_code => '45.925-000', :state => state); c.save; 
c = City.new(:name => 'Aritagua', :zip_code => '45.663-000', :state => state); c.save; 
c = City.new(:name => 'Aurelino Leal', :zip_code => '45.675-000', :state => state); c.save; 
c = City.new(:name => 'Baianopolis', :zip_code => '47.830-000', :state => state); c.save; 
c = City.new(:name => 'Baixa Do Palmeira', :zip_code => '44.535-000', :state => state); c.save; 
c = City.new(:name => 'Baixa Grande', :zip_code => '44.620-000', :state => state); c.save; 
c = City.new(:name => 'Baixao', :zip_code => '45.212-000', :state => state); c.save; 
c = City.new(:name => 'Baixinha', :zip_code => '45.313-000', :state => state); c.save; 
c = City.new(:name => 'Baluarte', :zip_code => '47.270-000', :state => state); c.save; 
c = City.new(:name => 'Banco Central', :zip_code => '45.673-000', :state => state); c.save; 
c = City.new(:name => 'Banco Da Vitoria', :zip_code => '45.661-000', :state => state); c.save; 
c = City.new(:name => 'Bandeira Do Almada', :zip_code => '45.635-000', :state => state); c.save; 
c = City.new(:name => 'Bandeira Do Colonia', :zip_code => '45.705-000', :state => state); c.save; 
c = City.new(:name => 'Banzae', :zip_code => '48.405-000', :state => state); c.save; 
c = City.new(:name => 'Baraunas', :zip_code => '46.920-000', :state => state); c.save; 
c = City.new(:name => 'Barcelos Do Sul', :zip_code => '45.448-000', :state => state); c.save; 
c = City.new(:name => 'Barra', :zip_code => '47.100-000', :state => state); c.save; 
c = City.new(:name => 'Barra Da Estiva', :zip_code => '46.650-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Choca', :zip_code => '45.120-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Mendes', :zip_code => '44.990-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Rocha', :zip_code => '45.560-000', :state => state); c.save; 
c = City.new(:name => 'Barreiras', :zip_code => '47.800-000', :state => state); c.save; 
c = City.new(:name => 'Barro Alto', :zip_code => '44.895-000', :state => state); c.save; 
c = City.new(:name => 'Barro Preto', :zip_code => '45.625-000', :state => state); c.save; 
c = City.new(:name => 'Barro Vermelho', :zip_code => '48.935-000', :state => state); c.save; 
c = City.new(:name => 'Barrocas', :zip_code => '48.705-000', :state => state); c.save; 
c = City.new(:name => 'Bastiao', :zip_code => '46.745-000', :state => state); c.save; 
c = City.new(:name => 'Batinga', :zip_code => '45.975-000', :state => state); c.save; 
c = City.new(:name => 'Bela Flor', :zip_code => '48.113-000', :state => state); c.save; 
c = City.new(:name => 'Belem Da Cachoeira', :zip_code => '44.315-000', :state => state); c.save; 
c = City.new(:name => 'Belmonte', :zip_code => '45.800-000', :state => state); c.save; 
c = City.new(:name => 'Belo Campo', :zip_code => '45.160-000', :state => state); c.save; 
c = City.new(:name => 'Belo Campo', :zip_code => '44.911-000', :state => state); c.save; 
c = City.new(:name => 'Bem-bom', :zip_code => '47.330-000', :state => state); c.save; 
c = City.new(:name => 'Bento Simoes', :zip_code => '44.258-000', :state => state); c.save; 
c = City.new(:name => 'Biritinga', :zip_code => '48.780-000', :state => state); c.save; 
c = City.new(:name => 'Boa Espera', :zip_code => '44.265-000', :state => state); c.save; 
c = City.new(:name => 'Boa Nova', :zip_code => '45.250-000', :state => state); c.save; 
c = City.new(:name => 'Boa Uniao', :zip_code => '48.103-000', :state => state); c.save; 
c = City.new(:name => 'Boa Vista Do Lagamar', :zip_code => '47.525-000', :state => state); c.save; 
c = City.new(:name => 'Boa Vista Do Tupim', :zip_code => '46.850-000', :state => state); c.save; 
c = City.new(:name => 'Boacu', :zip_code => '45.209-000', :state => state); c.save; 
c = City.new(:name => 'Boca Do Corrego', :zip_code => '45.805-000', :state => state); c.save; 
c = City.new(:name => 'Bom Jesus Da Lapa', :zip_code => '47.600-000', :state => state); c.save; 
c = City.new(:name => 'Bom Jesus Da Serra', :zip_code => '45.263-000', :state => state); c.save; 
c = City.new(:name => 'Bom Sossego', :zip_code => '47.540-000', :state => state); c.save; 
c = City.new(:name => 'Bonfim Da Feira', :zip_code => '44.120-000', :state => state); c.save; 
c = City.new(:name => 'Boninal', :zip_code => '46.740-000', :state => state); c.save; 
c = City.new(:name => 'Boquira', :zip_code => '46.530-000', :state => state); c.save; 
c = City.new(:name => 'Picarrao', :zip_code => '47.360-000', :state => state); c.save; 
c = City.new(:name => 'Botupora', :zip_code => '46.570-000', :state => state); c.save; 
c = City.new(:name => 'Botuquara', :zip_code => '46.475-000', :state => state); c.save; 
c = City.new(:name => 'Brejinho Das Ametistas', :zip_code => '46.405-000', :state => state); c.save; 
c = City.new(:name => 'Brejo Da Serra', :zip_code => '47.260-000', :state => state); c.save; 
c = City.new(:name => 'Brejo Novo', :zip_code => '46.855-000', :state => state); c.save; 
c = City.new(:name => 'Brejoes', :zip_code => '45.325-000', :state => state); c.save; 
c = City.new(:name => 'Brejolandia', :zip_code => '47.750-000', :state => state); c.save; 
c = City.new(:name => 'Brotas De Macaubas', :zip_code => '47.560-000', :state => state); c.save; 
c = City.new(:name => 'Brumado', :zip_code => '46.100-000', :state => state); c.save; 
c = City.new(:name => 'Bucuituba', :zip_code => '46.535-000', :state => state); c.save; 
c = City.new(:name => 'Buerarema', :zip_code => '45.615-000', :state => state); c.save; 
c = City.new(:name => 'Buracica', :zip_code => '44.285-000', :state => state); c.save; 
c = City.new(:name => 'Buranhem', :zip_code => '45.845-000', :state => state); c.save; 
c = City.new(:name => 'Buritirama', :zip_code => '47.120-000', :state => state); c.save; 
c = City.new(:name => 'Caatiba', :zip_code => '45.130-000', :state => state); c.save; 
c = City.new(:name => 'Cabaceiras Do Paraguacu', :zip_code => '44.345-000', :state => state); c.save; 
c = City.new(:name => 'Cabralia', :zip_code => '46.768-000', :state => state); c.save; 
c = City.new(:name => 'Cacha Pregos', :zip_code => '44.478-000', :state => state); c.save; 
c = City.new(:name => 'Cachoeira', :zip_code => '44.300-000', :state => state); c.save; 
c = City.new(:name => 'Cachoeira Do Mato', :zip_code => '45.999-000', :state => state); c.save; 
c = City.new(:name => 'Cacule', :zip_code => '46.300-000', :state => state); c.save; 
c = City.new(:name => 'Caem', :zip_code => '44.730-000', :state => state); c.save; 
c = City.new(:name => 'Caetanos', :zip_code => '45.265-000', :state => state); c.save; 
c = City.new(:name => 'Caete-acu', :zip_code => '46.940-000', :state => state); c.save; 
c = City.new(:name => 'Caetite', :zip_code => '46.400-000', :state => state); c.save; 
c = City.new(:name => 'Cafarnaum', :zip_code => '44.880-000', :state => state); c.save; 
c = City.new(:name => 'Cairu', :zip_code => '45.420-000', :state => state); c.save; 
c = City.new(:name => 'Caiubi', :zip_code => '45.858-000', :state => state); c.save; 
c = City.new(:name => 'Cajui', :zip_code => '47.390-000', :state => state); c.save; 
c = City.new(:name => 'Caldas Do Jorro', :zip_code => '48.793-000', :state => state); c.save; 
c = City.new(:name => 'Caldeirao', :zip_code => '48.955-000', :state => state); c.save; 
c = City.new(:name => 'Caldeirao Grande', :zip_code => '44.750-000', :state => state); c.save; 
c = City.new(:name => 'Caldeiras', :zip_code => '46.420-000', :state => state); c.save; 
c = City.new(:name => 'Camacan', :zip_code => '45.880-000', :state => state); c.save; 
c = City.new(:name => 'Camacari', :zip_code => '42.800-000', :state => state); c.save; 
c = City.new(:name => 'Camamu', :zip_code => '45.445-000', :state => state); c.save; 
c = City.new(:name => 'Camassandi', :zip_code => '44.482-000', :state => state); c.save; 
c = City.new(:name => 'Camirim', :zip_code => '44.860-000', :state => state); c.save; 
c = City.new(:name => 'Ribeirao Do Largo', :zip_code => '45.155-000', :state => state); c.save; 
c = City.new(:name => 'Campinhos', :zip_code => '44.215-000', :state => state); c.save; 
c = City.new(:name => 'Campo Alegre De Lourdes', :zip_code => '47.220-000', :state => state); c.save; 
c = City.new(:name => 'Campo Formoso', :zip_code => '44.790-000', :state => state); c.save; 
c = City.new(:name => 'Campo Formoso', :zip_code => '44.935-000', :state => state); c.save; 
c = City.new(:name => 'Camurugi', :zip_code => '45.434-000', :state => state); c.save; 
c = City.new(:name => 'Canabravinha', :zip_code => '46.195-000', :state => state); c.save; 
c = City.new(:name => 'Canapolis', :zip_code => '47.730-000', :state => state); c.save; 
c = City.new(:name => 'Canarana', :zip_code => '44.890-000', :state => state); c.save; 
c = City.new(:name => 'Canatiba', :zip_code => '46.510-000', :state => state); c.save; 
c = City.new(:name => 'Canavieiras', :zip_code => '45.860-000', :state => state); c.save; 
c = City.new(:name => 'Canche', :zip_code => '48.560-000', :state => state); c.save; 
c = City.new(:name => 'Candeal', :zip_code => '48.710-000', :state => state); c.save; 
c = City.new(:name => 'Candeias', :zip_code => '43.800-000', :state => state); c.save; 
c = City.new(:name => 'Candiba', :zip_code => '46.380-000', :state => state); c.save; 
c = City.new(:name => 'Candido Sales', :zip_code => '45.157-000', :state => state); c.save; 
c = City.new(:name => 'Cansancao', :zip_code => '48.840-000', :state => state); c.save; 
c = City.new(:name => 'Canudos', :zip_code => '48.520-000', :state => state); c.save; 
c = City.new(:name => 'Capao', :zip_code => '45.495-000', :state => state); c.save; 
c = City.new(:name => 'Capela Do Alto Alegre', :zip_code => '44.645-000', :state => state); c.save; 
c = City.new(:name => 'Capim Grosso', :zip_code => '44.695-000', :state => state); c.save; 
c = City.new(:name => 'Caraguatai', :zip_code => '46.680-000', :state => state); c.save; 
c = City.new(:name => 'Caraibas', :zip_code => '45.177-000', :state => state); c.save; 
c = City.new(:name => 'Caraibuna', :zip_code => '46.630-000', :state => state); c.save; 
c = City.new(:name => 'Caraipe', :zip_code => '44.555-000', :state => state); c.save; 
c = City.new(:name => 'Caraiva', :zip_code => '45.819-000', :state => state); c.save; 
c = City.new(:name => 'Caravelas', :zip_code => '45.900-000', :state => state); c.save; 
c = City.new(:name => 'Cardeal Da Silva', :zip_code => '48.390-000', :state => state); c.save; 
c = City.new(:name => 'Carinhanha', :zip_code => '46.445-000', :state => state); c.save; 
c = City.new(:name => 'Caripare', :zip_code => '47.980-000', :state => state); c.save; 
c = City.new(:name => 'Carnaiba Do Sertao', :zip_code => '48.922-000', :state => state); c.save; 
c = City.new(:name => 'Carrapichel', :zip_code => '48.985-000', :state => state); c.save; 
c = City.new(:name => 'Casa Nova', :zip_code => '47.300-000', :state => state); c.save; 
c = City.new(:name => 'Castelo Novo', :zip_code => '45.667-000', :state => state); c.save; 
c = City.new(:name => 'Castro Alves', :zip_code => '44.500-000', :state => state); c.save; 
c = City.new(:name => 'Catinga Do Moura', :zip_code => '44.704-000', :state => state); c.save; 
c = City.new(:name => 'Catingal', :zip_code => '45.245-000', :state => state); c.save; 
c = City.new(:name => 'Catolandia', :zip_code => '47.815-000', :state => state); c.save; 
c = City.new(:name => 'Catoles', :zip_code => '46.695-000', :state => state); c.save; 
c = City.new(:name => 'Catolezinho', :zip_code => '45.145-000', :state => state); c.save; 
c = City.new(:name => 'Catu', :zip_code => '48.110-000', :state => state); c.save; 
c = City.new(:name => 'Caturama', :zip_code => '46.575-000', :state => state); c.save; 
c = City.new(:name => 'Cavunge', :zip_code => '44.685-000', :state => state); c.save; 
c = City.new(:name => 'Central', :zip_code => '44.940-000', :state => state); c.save; 
c = City.new(:name => 'Ceraima', :zip_code => '46.433-000', :state => state); c.save; 
c = City.new(:name => 'Chorrocho', :zip_code => '48.660-000', :state => state); c.save; 
c = City.new(:name => 'Cicero Dantas', :zip_code => '48.410-000', :state => state); c.save; 
c = City.new(:name => 'Cinco Rios', :zip_code => '43.860-000', :state => state); c.save; 
c = City.new(:name => 'Cipo', :zip_code => '48.450-000', :state => state); c.save; 
c = City.new(:name => 'Coaraci', :zip_code => '45.638-000', :state => state); c.save; 
c = City.new(:name => 'Cocos', :zip_code => '47.680-000', :state => state); c.save; 
c = City.new(:name => 'Comercio', :zip_code => '44.545-000', :state => state); c.save; 
c = City.new(:name => 'Conceicao Da Feira', :zip_code => '44.320-000', :state => state); c.save; 
c = City.new(:name => 'Conceicao Do Almeida', :zip_code => '44.540-000', :state => state); c.save; 
c = City.new(:name => 'Conceicao Do Coite', :zip_code => '48.730-000', :state => state); c.save; 
c = City.new(:name => 'Conceicao Do Jacuipe', :zip_code => '44.245-000', :state => state); c.save; 
c = City.new(:name => 'Conde', :zip_code => '48.300-000', :state => state); c.save; 
c = City.new(:name => 'Condeuba', :zip_code => '46.200-000', :state => state); c.save; 
c = City.new(:name => 'Contendas Do Sincora', :zip_code => '46.620-000', :state => state); c.save; 
c = City.new(:name => 'Copixaba', :zip_code => '47.430-000', :state => state); c.save; 
c = City.new(:name => 'Coqueiros', :zip_code => '44.430-000', :state => state); c.save; 
c = City.new(:name => 'Coquinhos', :zip_code => '45.185-000', :state => state); c.save; 
c = City.new(:name => 'Coracao De Maria', :zip_code => '44.250-000', :state => state); c.save; 
c = City.new(:name => 'Cordeiros', :zip_code => '46.280-000', :state => state); c.save; 
c = City.new(:name => 'Coribe', :zip_code => '47.690-000', :state => state); c.save; 
c = City.new(:name => 'Coronel Joao Sa', :zip_code => '48.590-000', :state => state); c.save; 
c = City.new(:name => 'Correntina', :zip_code => '47.650-000', :state => state); c.save; 
c = City.new(:name => 'Corta Mao', :zip_code => '45.301-000', :state => state); c.save; 
c = City.new(:name => 'Cotegipe', :zip_code => '47.900-000', :state => state); c.save; 
c = City.new(:name => 'Coutos', :zip_code => '45.664-000', :state => state); c.save; 
c = City.new(:name => 'Cravolandia', :zip_code => '45.330-000', :state => state); c.save; 
c = City.new(:name => 'Crisopolis', :zip_code => '48.480-000', :state => state); c.save; 
c = City.new(:name => 'Cristalandia', :zip_code => '46.108-000', :state => state); c.save; 
c = City.new(:name => 'Cristopolis', :zip_code => '47.950-000', :state => state); c.save; 
c = City.new(:name => 'Crussai', :zip_code => '44.505-000', :state => state); c.save; 
c = City.new(:name => 'Cruz Das Almas', :zip_code => '44.380-000', :state => state); c.save; 
c = City.new(:name => 'Cumuruxatiba', :zip_code => '45.983-000', :state => state); c.save; 
c = City.new(:name => 'Cunhangi', :zip_code => '44.488-000', :state => state); c.save; 
c = City.new(:name => 'Curaca', :zip_code => '48.930-000', :state => state); c.save; 
c = City.new(:name => 'Dario Meira', :zip_code => '45.590-000', :state => state); c.save; 
c = City.new(:name => 'Delfino', :zip_code => '44.795-000', :state => state); c.save; 
c = City.new(:name => 'Dias Coelho', :zip_code => '44.855-000', :state => state); c.save; 
c = City.new(:name => 'Dias D Avila', :zip_code => '42.850-000', :state => state); c.save; 
c = City.new(:name => 'Diogenes Sampaio', :zip_code => '45.302-000', :state => state); c.save; 
c = City.new(:name => 'Dom Basilio', :zip_code => '46.165-000', :state => state); c.save; 
c = City.new(:name => 'Dom Macedo Costa', :zip_code => '44.560-000', :state => state); c.save; 
c = City.new(:name => 'Duas Barras Do Morro', :zip_code => '44.865-000', :state => state); c.save; 
c = City.new(:name => 'Elisio Medrado', :zip_code => '45.305-000', :state => state); c.save; 
c = City.new(:name => 'Encruzilhada', :zip_code => '45.150-000', :state => state); c.save; 
c = City.new(:name => 'Engenheiro Franca', :zip_code => '45.312-000', :state => state); c.save; 
c = City.new(:name => 'Engenheiro Pontes', :zip_code => '45.498-000', :state => state); c.save; 
c = City.new(:name => 'Entre Rios', :zip_code => '48.180-000', :state => state); c.save; 
c = City.new(:name => 'Esplanada', :zip_code => '48.370-000', :state => state); c.save; 
c = City.new(:name => 'Euclides Da Cunha', :zip_code => '48.500-000', :state => state); c.save; 
c = City.new(:name => 'Eunapolis', :zip_code => '45.820-000', :state => state); c.save; 
c = City.new(:name => 'Fatima', :zip_code => '48.415-000', :state => state); c.save; 
c = City.new(:name => 'Feira De Santana', :zip_code => '44.000-000', :state => state); c.save; 
c = City.new(:name => 'Ferradas', :zip_code => '45.600-000', :state => state); c.save; 
c = City.new(:name => 'Filadelfia', :zip_code => '44.775-000', :state => state); c.save; 
c = City.new(:name => 'Firmino Alves', :zip_code => '45.720-000', :state => state); c.save; 
c = City.new(:name => 'Floresta Azul', :zip_code => '45.740-000', :state => state); c.save; 
c = City.new(:name => 'Formosa Do Rio Preto', :zip_code => '47.990-000', :state => state); c.save; 
c = City.new(:name => 'Franca', :zip_code => '44.837-000', :state => state); c.save; 
c = City.new(:name => 'Gabiarra', :zip_code => '45.831-000', :state => state); c.save; 
c = City.new(:name => 'Galeao', :zip_code => '45.422-000', :state => state); c.save; 
c = City.new(:name => 'Gamboa', :zip_code => '45.424-000', :state => state); c.save; 
c = City.new(:name => 'Gameleira Da Lapa', :zip_code => '47.620-000', :state => state); c.save; 
c = City.new(:name => 'Gameleira Do Assurua', :zip_code => '47.470-000', :state => state); c.save; 
c = City.new(:name => 'Gandu', :zip_code => '45.450-000', :state => state); c.save; 
c = City.new(:name => 'Gaviao', :zip_code => '44.650-000', :state => state); c.save; 
c = City.new(:name => 'Gentio Do Ouro', :zip_code => '47.450-000', :state => state); c.save; 
c = City.new(:name => 'Geolandia', :zip_code => '44.349-000', :state => state); c.save; 
c = City.new(:name => 'Gloria', :zip_code => '48.610-000', :state => state); c.save; 
c = City.new(:name => 'Gongogi', :zip_code => '45.540-000', :state => state); c.save; 
c = City.new(:name => 'Governador Mangabeira', :zip_code => '44.350-000', :state => state); c.save; 
c = City.new(:name => 'Guai', :zip_code => '44.423-000', :state => state); c.save; 
c = City.new(:name => 'Guajeru', :zip_code => '46.205-000', :state => state); c.save; 
c = City.new(:name => 'Guanambi', :zip_code => '46.430-000', :state => state); c.save; 
c = City.new(:name => 'Guapira', :zip_code => '44.425-000', :state => state); c.save; 
c = City.new(:name => 'Guaratinga', :zip_code => '45.840-000', :state => state); c.save; 
c = City.new(:name => 'Presidente Tancredo Neves', :zip_code => '45.416-000', :state => state); c.save; 
c = City.new(:name => 'Guine', :zip_code => '46.753-000', :state => state); c.save; 
c = City.new(:name => 'Guirapa', :zip_code => '46.370-000', :state => state); c.save; 
c = City.new(:name => 'Gurupa Mirim', :zip_code => '45.795-000', :state => state); c.save; 
c = City.new(:name => 'Heliopolis', :zip_code => '48.445-000', :state => state); c.save; 
c = City.new(:name => 'Helvecia', :zip_code => '45.923-000', :state => state); c.save; 
c = City.new(:name => 'Hidrolandia', :zip_code => '44.955-000', :state => state); c.save; 
c = City.new(:name => 'Humildes', :zip_code => '44.135-000', :state => state); c.save; 
c = City.new(:name => 'Iacu', :zip_code => '46.860-000', :state => state); c.save; 
c = City.new(:name => 'Ibatui', :zip_code => '48.185-000', :state => state); c.save; 
c = City.new(:name => 'Ibiacu', :zip_code => '45.523-000', :state => state); c.save; 
c = City.new(:name => 'Ibiajara', :zip_code => '46.560-000', :state => state); c.save; 
c = City.new(:name => 'Ibiapora', :zip_code => '44.825-000', :state => state); c.save; 
c = City.new(:name => 'Ibiassuce', :zip_code => '46.390-000', :state => state); c.save; 
c = City.new(:name => 'Ibicarai', :zip_code => '45.745-000', :state => state); c.save; 
c = City.new(:name => 'Ibicoara', :zip_code => '46.760-000', :state => state); c.save; 
c = City.new(:name => 'Ibicui', :zip_code => '45.290-000', :state => state); c.save; 
c = City.new(:name => 'Ibipeba', :zip_code => '44.970-000', :state => state); c.save; 
c = City.new(:name => 'Ibipetum', :zip_code => '47.595-000', :state => state); c.save; 
c = City.new(:name => 'Ibipitanga', :zip_code => '46.540-000', :state => state); c.save; 
c = City.new(:name => 'Ibiquera', :zip_code => '46.840-000', :state => state); c.save; 
c = City.new(:name => 'Ibiraba', :zip_code => '47.110-000', :state => state); c.save; 
c = City.new(:name => 'Ibiraja', :zip_code => '45.972-000', :state => state); c.save; 
c = City.new(:name => 'Ibiranhem', :zip_code => '45.938-000', :state => state); c.save; 
c = City.new(:name => 'Ibirapitanga', :zip_code => '45.500-000', :state => state); c.save; 
c = City.new(:name => 'Ibirapua', :zip_code => '45.940-000', :state => state); c.save; 
c = City.new(:name => 'Ibirataia', :zip_code => '45.580-000', :state => state); c.save; 
c = City.new(:name => 'Ibitiara', :zip_code => '46.700-000', :state => state); c.save; 
c = City.new(:name => 'Ibitiguira', :zip_code => '45.378-000', :state => state); c.save; 
c = City.new(:name => 'Ibitira', :zip_code => '46.225-000', :state => state); c.save; 
c = City.new(:name => 'Ibitita', :zip_code => '44.960-000', :state => state); c.save; 
c = City.new(:name => 'Ibitunane', :zip_code => '47.480-000', :state => state); c.save; 
c = City.new(:name => 'Ibitupa', :zip_code => '45.298-000', :state => state); c.save; 
c = City.new(:name => 'Ibo', :zip_code => '48.685-000', :state => state); c.save; 
c = City.new(:name => 'Ibotirama', :zip_code => '47.520-000', :state => state); c.save; 
c = City.new(:name => 'Ichu', :zip_code => '48.725-000', :state => state); c.save; 
c = City.new(:name => 'Igapora', :zip_code => '46.490-000', :state => state); c.save; 
c = City.new(:name => 'Igara', :zip_code => '48.975-000', :state => state); c.save; 
c = City.new(:name => 'Igarite', :zip_code => '47.105-000', :state => state); c.save; 
c = City.new(:name => 'Igatu', :zip_code => '46.834-000', :state => state); c.save; 
c = City.new(:name => 'Igrapiuna', :zip_code => '45.443-000', :state => state); c.save; 
c = City.new(:name => 'Igua', :zip_code => '45.105-000', :state => state); c.save; 
c = City.new(:name => 'Iguai', :zip_code => '45.280-000', :state => state); c.save; 
c = City.new(:name => 'Iguaibi', :zip_code => '45.285-000', :state => state); c.save; 
c = City.new(:name => 'Iguatemi', :zip_code => '46.150-000', :state => state); c.save; 
c = City.new(:name => 'Iguira', :zip_code => '47.410-000', :state => state); c.save; 
c = City.new(:name => 'Iguitu', :zip_code => '44.975-000', :state => state); c.save; 
c = City.new(:name => 'Ilheus', :zip_code => '45.650-000', :state => state); c.save; 
c = City.new(:name => 'Indai', :zip_code => '44.810-000', :state => state); c.save; 
c = City.new(:name => 'Inema', :zip_code => '45.669-000', :state => state); c.save; 
c = City.new(:name => 'Inhambupe', :zip_code => '48.490-000', :state => state); c.save; 
c = City.new(:name => 'Inhata', :zip_code => '44.235-000', :state => state); c.save; 
c = City.new(:name => 'Inhaumas', :zip_code => '47.648-000', :state => state); c.save; 
c = City.new(:name => 'Inhobim', :zip_code => '45.110-000', :state => state); c.save; 
c = City.new(:name => 'Inubia', :zip_code => '46.766-000', :state => state); c.save; 
c = City.new(:name => 'Ipecaeta', :zip_code => '44.680-000', :state => state); c.save; 
c = City.new(:name => 'Ipiau', :zip_code => '45.570-000', :state => state); c.save; 
c = City.new(:name => 'Ipira', :zip_code => '44.600-000', :state => state); c.save; 
c = City.new(:name => 'Ipiuna', :zip_code => '45.347-000', :state => state); c.save; 
c = City.new(:name => 'Governador Joao Durval Carneiro', :zip_code => '44.130-000', :state => state); c.save; 
c = City.new(:name => 'Ipucaba', :zip_code => '47.550-000', :state => state); c.save; 
c = City.new(:name => 'Ipupiara', :zip_code => '47.590-000', :state => state); c.save; 
c = City.new(:name => 'Irajuba', :zip_code => '45.370-000', :state => state); c.save; 
c = City.new(:name => 'Iramaia', :zip_code => '46.770-000', :state => state); c.save; 
c = City.new(:name => 'Iraporanga', :zip_code => '46.985-000', :state => state); c.save; 
c = City.new(:name => 'Iraquara', :zip_code => '46.980-000', :state => state); c.save; 
c = City.new(:name => 'Irara', :zip_code => '44.255-000', :state => state); c.save; 
c = City.new(:name => 'Irece', :zip_code => '44.900-000', :state => state); c.save; 
c = City.new(:name => 'Irundiara', :zip_code => '46.315-000', :state => state); c.save; 
c = City.new(:name => 'Itabela', :zip_code => '45.848-000', :state => state); c.save; 
c = City.new(:name => 'Itaberaba', :zip_code => '46.880-000', :state => state); c.save; 
c = City.new(:name => 'Itabuna', :zip_code => '45.600-000', :state => state); c.save; 
c = City.new(:name => 'Itacare', :zip_code => '45.530-000', :state => state); c.save; 
c = City.new(:name => 'Itacava', :zip_code => '44.253-000', :state => state); c.save; 
c = City.new(:name => 'Itachama', :zip_code => '45.303-000', :state => state); c.save; 
c = City.new(:name => 'Itaete', :zip_code => '46.790-000', :state => state); c.save; 
c = City.new(:name => 'Itagi', :zip_code => '45.230-000', :state => state); c.save; 
c = City.new(:name => 'Itagiba', :zip_code => '45.585-000', :state => state); c.save; 
c = City.new(:name => 'Itagimirim', :zip_code => '45.850-000', :state => state); c.save; 
c = City.new(:name => 'Itaia', :zip_code => '45.723-000', :state => state); c.save; 
c = City.new(:name => 'Itaibo', :zip_code => '45.213-000', :state => state); c.save; 
c = City.new(:name => 'Itaitu', :zip_code => '44.702-000', :state => state); c.save; 
c = City.new(:name => 'Itajai', :zip_code => '45.275-000', :state => state); c.save; 
c = City.new(:name => 'Itaju Do Colonia', :zip_code => '45.730-000', :state => state); c.save; 
c = City.new(:name => 'Itajubaquara', :zip_code => '47.460-000', :state => state); c.save; 
c = City.new(:name => 'Itajuipe', :zip_code => '45.630-000', :state => state); c.save; 
c = City.new(:name => 'Itajuru', :zip_code => '45.211-000', :state => state); c.save; 
c = City.new(:name => 'Itamaraju', :zip_code => '45.836-000', :state => state); c.save; 
c = City.new(:name => 'Itamari', :zip_code => '45.455-000', :state => state); c.save; 
c = City.new(:name => 'Itambe', :zip_code => '45.140-000', :state => state); c.save; 
c = City.new(:name => 'Itamira', :zip_code => '48.355-000', :state => state); c.save; 
c = City.new(:name => 'Itamotinga', :zip_code => '48.920-000', :state => state); c.save; 
c = City.new(:name => 'Itanage', :zip_code => '46.143-000', :state => state); c.save; 
c = City.new(:name => 'Itanagra', :zip_code => '48.290-000', :state => state); c.save; 
c = City.new(:name => 'Itanhem', :zip_code => '45.970-000', :state => state); c.save; 
c = City.new(:name => 'Itanhi', :zip_code => '48.315-000', :state => state); c.save; 
c = City.new(:name => 'Itaparica', :zip_code => '44.460-000', :state => state); c.save; 
c = City.new(:name => 'Itape', :zip_code => '45.750-000', :state => state); c.save; 
c = City.new(:name => 'Itapebi', :zip_code => '45.855-000', :state => state); c.save; 
c = City.new(:name => 'Itapeipu', :zip_code => '44.708-000', :state => state); c.save; 
c = City.new(:name => 'Itapetinga', :zip_code => '45.700-000', :state => state); c.save; 
c = City.new(:name => 'Itapicuru', :zip_code => '48.475-000', :state => state); c.save; 
c = City.new(:name => 'Itapitanga', :zip_code => '45.645-000', :state => state); c.save; 
c = City.new(:name => 'Itapora', :zip_code => '44.343-000', :state => state); c.save; 
c = City.new(:name => 'Itapura', :zip_code => '44.727-000', :state => state); c.save; 
c = City.new(:name => 'Itaquara', :zip_code => '45.340-000', :state => state); c.save; 
c = City.new(:name => 'Itaquarai', :zip_code => '46.103-000', :state => state); c.save; 
c = City.new(:name => 'Itarantim', :zip_code => '45.780-000', :state => state); c.save; 
c = City.new(:name => 'Itatim', :zip_code => '46.875-000', :state => state); c.save; 
c = City.new(:name => 'Itatingui', :zip_code => '45.698-000', :state => state); c.save; 
c = City.new(:name => 'Itirucu', :zip_code => '45.350-000', :state => state); c.save; 
c = City.new(:name => 'Itiuba', :zip_code => '48.850-000', :state => state); c.save; 
c = City.new(:name => 'Itororo', :zip_code => '45.710-000', :state => state); c.save; 
c = City.new(:name => 'Ituacu', :zip_code => '46.640-000', :state => state); c.save; 
c = City.new(:name => 'Itubera', :zip_code => '45.435-000', :state => state); c.save; 
c = City.new(:name => 'Itupeva', :zip_code => '45.968-000', :state => state); c.save; 
c = City.new(:name => 'Jaborandi', :zip_code => '47.655-000', :state => state); c.save; 
c = City.new(:name => 'Jacaraci', :zip_code => '46.310-000', :state => state); c.save; 
c = City.new(:name => 'Jacobina', :zip_code => '44.700-000', :state => state); c.save; 
c = City.new(:name => 'Jacu', :zip_code => '44.273-000', :state => state); c.save; 
c = City.new(:name => 'Jacuipe', :zip_code => '43.870-000', :state => state); c.save; 
c = City.new(:name => 'Jacuruna', :zip_code => '44.484-000', :state => state); c.save; 
c = City.new(:name => 'Jaguaquara', :zip_code => '45.345-000', :state => state); c.save; 
c = City.new(:name => 'Jaguara', :zip_code => '44.125-000', :state => state); c.save; 
c = City.new(:name => 'Jaguarari', :zip_code => '48.960-000', :state => state); c.save; 
c = City.new(:name => 'Jaguaripe', :zip_code => '44.480-000', :state => state); c.save; 
c = City.new(:name => 'Jaiba', :zip_code => '44.115-000', :state => state); c.save; 
c = City.new(:name => 'Jandaira', :zip_code => '48.310-000', :state => state); c.save; 
c = City.new(:name => 'Japomirim', :zip_code => '45.588-000', :state => state); c.save; 
c = City.new(:name => 'Japu', :zip_code => '45.665-000', :state => state); c.save; 
c = City.new(:name => 'Jequie', :zip_code => '45.200-000', :state => state); c.save; 
c = City.new(:name => 'Jeremoabo', :zip_code => '48.540-000', :state => state); c.save; 
c = City.new(:name => 'Jequirica', :zip_code => '45.470-000', :state => state); c.save; 
c = City.new(:name => 'Jiribatuba', :zip_code => '44.475-000', :state => state); c.save; 
c = City.new(:name => 'Jitauna', :zip_code => '45.225-000', :state => state); c.save; 
c = City.new(:name => 'Joao Amaro', :zip_code => '46.865-000', :state => state); c.save; 
c = City.new(:name => 'Joao Correia', :zip_code => '46.755-000', :state => state); c.save; 
c = City.new(:name => 'Joao Dourado', :zip_code => '44.920-000', :state => state); c.save; 
c = City.new(:name => 'Jose Goncalves', :zip_code => '45.115-000', :state => state); c.save; 
c = City.new(:name => 'Juacema', :zip_code => '48.965-000', :state => state); c.save; 
c = City.new(:name => 'Juazeiro', :zip_code => '48.900-000', :state => state); c.save; 
c = City.new(:name => 'Jucurucu', :zip_code => '45.834-000', :state => state); c.save; 
c = City.new(:name => 'Juerana', :zip_code => '45.910-000', :state => state); c.save; 
c = City.new(:name => 'Junco', :zip_code => '48.910-000', :state => state); c.save; 
c = City.new(:name => 'Jupagua', :zip_code => '47.920-000', :state => state); c.save; 
c = City.new(:name => 'Juraci', :zip_code => '46.785-000', :state => state); c.save; 
c = City.new(:name => 'Juremal', :zip_code => '48.915-000', :state => state); c.save; 
c = City.new(:name => 'Jussara', :zip_code => '44.925-000', :state => state); c.save; 
c = City.new(:name => 'Jussari', :zip_code => '45.610-000', :state => state); c.save; 
c = City.new(:name => 'Jussiape', :zip_code => '46.670-000', :state => state); c.save; 
c = City.new(:name => 'Lafaiete Coutinho', :zip_code => '45.215-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Clara', :zip_code => '46.520-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Do Boi', :zip_code => '44.898-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Preta', :zip_code => '45.175-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Real', :zip_code => '46.425-000', :state => state); c.save; 
c = City.new(:name => 'Laje', :zip_code => '45.490-000', :state => state); c.save; 
c = City.new(:name => 'Laje Do Banco', :zip_code => '45.676-000', :state => state); c.save; 
c = City.new(:name => 'Lajedao', :zip_code => '45.950-000', :state => state); c.save; 
c = City.new(:name => 'Lajedinho', :zip_code => '46.825-000', :state => state); c.save; 
c = City.new(:name => 'Lajedo Alto', :zip_code => '46.868-000', :state => state); c.save; 
c = City.new(:name => 'Lajedo Do Tabocal', :zip_code => '45.365-000', :state => state); c.save; 
c = City.new(:name => 'Lamarao', :zip_code => '48.720-000', :state => state); c.save; 
c = City.new(:name => 'Lamarao Do Passe', :zip_code => '43.855-000', :state => state); c.save; 
c = City.new(:name => 'Lapao', :zip_code => '44.905-000', :state => state); c.save; 
c = City.new(:name => 'Largo', :zip_code => '44.835-000', :state => state); c.save; 
c = City.new(:name => 'Lauro De Freitas', :zip_code => '42.700-000', :state => state); c.save; 
c = City.new(:name => 'Lencois', :zip_code => '46.960-000', :state => state); c.save; 
c = City.new(:name => 'Licinio De Almeida', :zip_code => '46.330-000', :state => state); c.save; 
c = City.new(:name => 'Livramento Do Brumado', :zip_code => '46.140-000', :state => state); c.save; 
c = City.new(:name => 'Lucaia', :zip_code => '45.195-000', :state => state); c.save; 
c = City.new(:name => 'Luis Viana', :zip_code => '47.340-000', :state => state); c.save; 
c = City.new(:name => 'Lustosa', :zip_code => '44.283-000', :state => state); c.save; 
c = City.new(:name => 'Macajuba', :zip_code => '46.805-000', :state => state); c.save; 
c = City.new(:name => 'Macarani', :zip_code => '45.760-000', :state => state); c.save; 
c = City.new(:name => 'Macaubas', :zip_code => '46.500-000', :state => state); c.save; 
c = City.new(:name => 'Macurure', :zip_code => '48.650-000', :state => state); c.save; 
c = City.new(:name => 'Madre De Deus', :zip_code => '42.600-000', :state => state); c.save; 
c = City.new(:name => 'Maetinga', :zip_code => '46.255-000', :state => state); c.save; 
c = City.new(:name => 'Maiquinique', :zip_code => '45.770-000', :state => state); c.save; 
c = City.new(:name => 'Mairi', :zip_code => '44.630-000', :state => state); c.save; 
c = City.new(:name => 'Malhada', :zip_code => '46.440-000', :state => state); c.save; 
c = City.new(:name => 'Malhada De Pedras', :zip_code => '46.110-000', :state => state); c.save; 
c = City.new(:name => 'Mandiroba', :zip_code => '46.455-000', :state => state); c.save; 
c = City.new(:name => 'Mangue Seco', :zip_code => '48.325-000', :state => state); c.save; 
c = City.new(:name => 'Maniacu', :zip_code => '46.410-000', :state => state); c.save; 
c = City.new(:name => 'Manoel Vitorino', :zip_code => '45.240-000', :state => state); c.save; 
c = City.new(:name => 'Mansidao', :zip_code => '47.160-000', :state => state); c.save; 
c = City.new(:name => 'Mar Grande', :zip_code => '44.473-000', :state => state); c.save; 
c = City.new(:name => 'Maracas', :zip_code => '45.360-000', :state => state); c.save; 
c = City.new(:name => 'Maragogipe', :zip_code => '44.420-000', :state => state); c.save; 
c = City.new(:name => 'Maragogipinho', :zip_code => '44.495-000', :state => state); c.save; 
c = City.new(:name => 'Marau', :zip_code => '45.520-000', :state => state); c.save; 
c = City.new(:name => 'Marcionilio Souza', :zip_code => '46.780-000', :state => state); c.save; 
c = City.new(:name => 'Marcolino Moura', :zip_code => '46.175-000', :state => state); c.save; 
c = City.new(:name => 'Maria Quiteria', :zip_code => '44.110-000', :state => state); c.save; 
c = City.new(:name => 'Maricoabo', :zip_code => '45.412-000', :state => state); c.save; 
c = City.new(:name => 'Mariquita', :zip_code => '47.770-000', :state => state); c.save; 
c = City.new(:name => 'Mascote', :zip_code => '45.870-000', :state => state); c.save; 
c = City.new(:name => 'Massacara', :zip_code => '48.510-000', :state => state); c.save; 
c = City.new(:name => 'Massaroca', :zip_code => '48.918-000', :state => state); c.save; 
c = City.new(:name => 'Feira Da Mata', :zip_code => '46.446-000', :state => state); c.save; 
c = City.new(:name => 'Mata Da Alianca', :zip_code => '44.240-000', :state => state); c.save; 
c = City.new(:name => 'Mata De Sao Joao', :zip_code => '48.280-000', :state => state); c.save; 
c = City.new(:name => 'Mataripe', :zip_code => '43.970-000', :state => state); c.save; 
c = City.new(:name => 'Matina', :zip_code => '46.480-000', :state => state); c.save; 
c = City.new(:name => 'Medeiros Neto', :zip_code => '45.960-000', :state => state); c.save; 
c = City.new(:name => 'Miguel Calmon', :zip_code => '44.720-000', :state => state); c.save; 
c = City.new(:name => 'Milagres', :zip_code => '45.315-000', :state => state); c.save; 
c = City.new(:name => 'Minas Do Espirito Santo', :zip_code => '44.995-000', :state => state); c.save; 
c = City.new(:name => 'Minas Do Mimoso', :zip_code => '47.375-000', :state => state); c.save; 
c = City.new(:name => 'Mirandela', :zip_code => '48.409-000', :state => state); c.save; 
c = City.new(:name => 'Miranga', :zip_code => '48.126-000', :state => state); c.save; 
c = City.new(:name => 'Mirangaba', :zip_code => '44.745-000', :state => state); c.save; 
c = City.new(:name => 'Mirante', :zip_code => '45.255-000', :state => state); c.save; 
c = City.new(:name => 'Mogiquicaba', :zip_code => '45.803-000', :state => state); c.save; 
c = City.new(:name => 'Monte Cruzeiro', :zip_code => '45.306-000', :state => state); c.save; 
c = City.new(:name => 'Monte Gordo', :zip_code => '42.820-000', :state => state); c.save; 
c = City.new(:name => 'Monte Reconcavo', :zip_code => '43.980-000', :state => state); c.save; 
c = City.new(:name => 'Monte Santo', :zip_code => '48.800-000', :state => state); c.save; 
c = City.new(:name => 'Morpara', :zip_code => '47.580-000', :state => state); c.save; 
c = City.new(:name => 'Morro Das Flores', :zip_code => '46.802-000', :state => state); c.save; 
c = City.new(:name => 'Morro Do Chapeu', :zip_code => '44.850-000', :state => state); c.save; 
c = City.new(:name => 'Mortugaba', :zip_code => '46.290-000', :state => state); c.save; 
c = City.new(:name => 'Mucuge', :zip_code => '46.750-000', :state => state); c.save; 
c = City.new(:name => 'Mucuri', :zip_code => '45.930-000', :state => state); c.save; 
c = City.new(:name => 'Mulungu Do Morro', :zip_code => '44.885-000', :state => state); c.save; 
c = City.new(:name => 'Mundo Novo', :zip_code => '44.800-000', :state => state); c.save; 
c = City.new(:name => 'Muniz Ferreira', :zip_code => '44.575-000', :state => state); c.save; 
c = City.new(:name => 'Muritiba', :zip_code => '44.340-000', :state => state); c.save; 
c = City.new(:name => 'Mutas', :zip_code => '46.436-000', :state => state); c.save; 
c = City.new(:name => 'Mutuipe', :zip_code => '45.480-000', :state => state); c.save; 
c = City.new(:name => 'Nage', :zip_code => '44.432-000', :state => state); c.save; 
c = City.new(:name => 'Nazare', :zip_code => '44.400-000', :state => state); c.save; 
c = City.new(:name => 'Nilo Pecanha', :zip_code => '45.440-000', :state => state); c.save; 
c = City.new(:name => 'Nordestina', :zip_code => '48.870-000', :state => state); c.save; 
c = City.new(:name => 'Nova Canaa', :zip_code => '45.270-000', :state => state); c.save; 
c = City.new(:name => 'Nova Ibia', :zip_code => '45.452-000', :state => state); c.save; 
c = City.new(:name => 'Nova Itaipe', :zip_code => '45.380-000', :state => state); c.save; 
c = City.new(:name => 'Nova Itarana', :zip_code => '45.390-000', :state => state); c.save; 
c = City.new(:name => 'Nova Lidice', :zip_code => '45.965-000', :state => state); c.save; 
c = City.new(:name => 'Nova Redencao', :zip_code => '46.835-000', :state => state); c.save; 
c = City.new(:name => 'Nova Soure', :zip_code => '48.460-000', :state => state); c.save; 
c = City.new(:name => 'Nova Vicosa', :zip_code => '45.920-000', :state => state); c.save; 
c = City.new(:name => 'Novo Acre', :zip_code => '46.775-000', :state => state); c.save; 
c = City.new(:name => 'Nucleo Residencial Pilar', :zip_code => '48.967-000', :state => state); c.save; 
c = City.new(:name => 'Nuguacu', :zip_code => '44.747-000', :state => state); c.save; 
c = City.new(:name => 'Olhos Dagua Do Serafim', :zip_code => '46.735-000', :state => state); c.save; 
c = City.new(:name => 'Olindina', :zip_code => '48.470-000', :state => state); c.save; 
c = City.new(:name => 'Oliveira Dos Brejinhos', :zip_code => '47.530-000', :state => state); c.save; 
c = City.new(:name => 'Olivenca', :zip_code => '45.668-000', :state => state); c.save; 
c = City.new(:name => 'Onha', :zip_code => '44.578-000', :state => state); c.save; 
c = City.new(:name => 'Oriente Novo', :zip_code => '45.210-000', :state => state); c.save; 
c = City.new(:name => 'Ouricana', :zip_code => '45.863-000', :state => state); c.save; 
c = City.new(:name => 'Ouricangas', :zip_code => '48.150-000', :state => state); c.save; 
c = City.new(:name => 'Ouricuri Do Ouro', :zip_code => '47.565-000', :state => state); c.save; 
c = City.new(:name => 'Ourolandia', :zip_code => '44.718-000', :state => state); c.save; 
c = City.new(:name => 'Outeiro Redondo', :zip_code => '44.365-000', :state => state); c.save; 
c = City.new(:name => 'Paiol', :zip_code => '46.320-000', :state => state); c.save; 
c = City.new(:name => 'Pajeu Do Vento', :zip_code => '46.402-000', :state => state); c.save; 
c = City.new(:name => 'Palame', :zip_code => '48.380-000', :state => state); c.save; 
c = City.new(:name => 'Palmas De Monte Alto', :zip_code => '46.460-000', :state => state); c.save; 
c = City.new(:name => 'Palmeiras', :zip_code => '46.930-000', :state => state); c.save; 
c = City.new(:name => 'Paramirim', :zip_code => '46.190-000', :state => state); c.save; 
c = City.new(:name => 'Parateca', :zip_code => '46.443-000', :state => state); c.save; 
c = City.new(:name => 'Paratinga', :zip_code => '47.500-000', :state => state); c.save; 
c = City.new(:name => 'Paripiranga', :zip_code => '48.430-000', :state => state); c.save; 
c = City.new(:name => 'Pataiba', :zip_code => '48.175-000', :state => state); c.save; 
c = City.new(:name => 'Patamute', :zip_code => '48.945-000', :state => state); c.save; 
c = City.new(:name => 'Pau A Pique', :zip_code => '47.320-000', :state => state); c.save; 
c = City.new(:name => 'Pau Brasil', :zip_code => '45.890-000', :state => state); c.save; 
c = City.new(:name => 'Paulo Afonso', :zip_code => '48.600-000', :state => state); c.save; 
c = City.new(:name => 'Pe De Serra', :zip_code => '44.655-000', :state => state); c.save; 
c = City.new(:name => 'Pedrao', :zip_code => '48.140-000', :state => state); c.save; 
c = City.new(:name => 'Pedro Alexandre', :zip_code => '48.580-000', :state => state); c.save; 
c = City.new(:name => 'Peixe', :zip_code => '47.230-000', :state => state); c.save; 
c = City.new(:name => 'Petim', :zip_code => '44.510-000', :state => state); c.save; 
c = City.new(:name => 'Piabanha', :zip_code => '45.525-000', :state => state); c.save; 
c = City.new(:name => 'Piata', :zip_code => '46.765-000', :state => state); c.save; 
c = City.new(:name => 'Pilao Arcado', :zip_code => '47.240-000', :state => state); c.save; 
c = City.new(:name => 'Pimenteira', :zip_code => '45.672-000', :state => state); c.save; 
c = City.new(:name => 'Pindai', :zip_code => '46.360-000', :state => state); c.save; 
c = City.new(:name => 'Pindobacu', :zip_code => '44.770-000', :state => state); c.save; 
c = City.new(:name => 'Pintadas', :zip_code => '44.610-000', :state => state); c.save; 
c = City.new(:name => 'Muquem Do Sao Francisco', :zip_code => '47.115-000', :state => state); c.save; 
c = City.new(:name => 'Pirai Do Norte', :zip_code => '45.436-000', :state => state); c.save; 
c = City.new(:name => 'Pirajuia', :zip_code => '44.486-000', :state => state); c.save; 
c = City.new(:name => 'Piri', :zip_code => '47.355-000', :state => state); c.save; 
c = City.new(:name => 'Piripa', :zip_code => '46.270-000', :state => state); c.save; 
c = City.new(:name => 'Piritiba', :zip_code => '44.830-000', :state => state); c.save; 
c = City.new(:name => 'Planaltino', :zip_code => '45.375-000', :state => state); c.save; 
c = City.new(:name => 'Planalto', :zip_code => '45.190-000', :state => state); c.save; 
c = City.new(:name => 'Poco Central', :zip_code => '45.678-000', :state => state); c.save; 
c = City.new(:name => 'Poco De Fora', :zip_code => '48.940-000', :state => state); c.save; 
c = City.new(:name => 'Pocoes', :zip_code => '45.260-000', :state => state); c.save; 
c = City.new(:name => 'Pocos', :zip_code => '47.210-000', :state => state); c.save; 
c = City.new(:name => 'Pojuca', :zip_code => '48.120-000', :state => state); c.save; 
c = City.new(:name => 'Polo Petroquimico De Camacari', :zip_code => '42.800-000', :state => state); c.save; 
c = City.new(:name => 'Ponta Da Areia', :zip_code => '45.905-000', :state => state); c.save; 
c = City.new(:name => 'Ponto Novo', :zip_code => '44.755-000', :state => state); c.save; 
c = City.new(:name => 'Porto Novo', :zip_code => '47.710-000', :state => state); c.save; 
c = City.new(:name => 'Porto Seguro', :zip_code => '45.810-000', :state => state); c.save; 
c = City.new(:name => 'Posto Da Mata', :zip_code => '45.928-000', :state => state); c.save; 
c = City.new(:name => 'Potiragua', :zip_code => '45.790-000', :state => state); c.save; 
c = City.new(:name => 'Poxim Do Sul', :zip_code => '45.862-000', :state => state); c.save; 
c = City.new(:name => 'Prado', :zip_code => '45.980-000', :state => state); c.save; 
c = City.new(:name => 'Presidente Dutra', :zip_code => '44.930-000', :state => state); c.save; 
c = City.new(:name => 'Presidente Janio Quadros', :zip_code => '46.250-000', :state => state); c.save; 
c = City.new(:name => 'Prevenido', :zip_code => '44.912-000', :state => state); c.save; 
c = City.new(:name => 'Queimadas', :zip_code => '48.860-000', :state => state); c.save; 
c = City.new(:name => 'Quijingue', :zip_code => '48.830-000', :state => state); c.save; 
c = City.new(:name => 'Quixaba', :zip_code => '47.585-000', :state => state); c.save; 
c = City.new(:name => 'Rafael Jambeiro', :zip_code => '44.520-000', :state => state); c.save; 
c = City.new(:name => 'Recife', :zip_code => '44.927-000', :state => state); c.save; 
c = City.new(:name => 'Remanso', :zip_code => '47.200-000', :state => state); c.save; 
c = City.new(:name => 'Remedios', :zip_code => '46.738-000', :state => state); c.save; 
c = City.new(:name => 'Retirolandia', :zip_code => '48.750-000', :state => state); c.save; 
c = City.new(:name => 'Riachao Das Neves', :zip_code => '47.970-000', :state => state); c.save; 
c = City.new(:name => 'Riachao Do Jacuipe', :zip_code => '44.640-000', :state => state); c.save; 
c = City.new(:name => 'Riachao Do Utinga', :zip_code => '46.815-000', :state => state); c.save; 
c = City.new(:name => 'Riacho Da Guia', :zip_code => '48.105-000', :state => state); c.save; 
c = City.new(:name => 'Riacho De Santana', :zip_code => '46.470-000', :state => state); c.save; 
c = City.new(:name => 'Riacho Seco', :zip_code => '48.933-000', :state => state); c.save; 
c = City.new(:name => 'Ribeira Do Amparo', :zip_code => '48.440-000', :state => state); c.save; 
c = City.new(:name => 'Ribeira Do Pombal', :zip_code => '48.400-000', :state => state); c.save; 
c = City.new(:name => 'Ribeirao Do Salto', :zip_code => '45.785-000', :state => state); c.save; 
c = City.new(:name => 'Rio Da Dona', :zip_code => '44.548-000', :state => state); c.save; 
c = City.new(:name => 'Rio De Contas', :zip_code => '46.170-000', :state => state); c.save; 
c = City.new(:name => 'Rio Do Antonio', :zip_code => '46.220-000', :state => state); c.save; 
c = City.new(:name => 'Rio Do Braco', :zip_code => '45.666-000', :state => state); c.save; 
c = City.new(:name => 'Rio Do Pires', :zip_code => '46.550-000', :state => state); c.save; 
c = City.new(:name => 'Rio Fundo', :zip_code => '44.275-000', :state => state); c.save; 
c = City.new(:name => 'Rio Real', :zip_code => '48.330-000', :state => state); c.save; 
c = City.new(:name => 'Rodelas', :zip_code => '48.630-000', :state => state); c.save; 
c = City.new(:name => 'Ruy Barbosa', :zip_code => '46.800-000', :state => state); c.save; 
c = City.new(:name => 'Saldanha', :zip_code => '47.250-000', :state => state); c.save; 
c = City.new(:name => 'Salgadalia', :zip_code => '48.740-000', :state => state); c.save; 
c = City.new(:name => 'Salinas Da Margarida', :zip_code => '44.450-000', :state => state); c.save; 
c = City.new(:name => 'Salobrinho', :zip_code => '45.662-000', :state => state); c.save; 
c = City.new(:name => 'Salvador', :zip_code => '40.000-000', :state => state); c.save; 
c = City.new(:name => 'Sambaiba', :zip_code => '48.476-000', :state => state); c.save; 
c = City.new(:name => 'Santa Barbara', :zip_code => '44.150-000', :state => state); c.save; 
c = City.new(:name => 'Santa Brigida', :zip_code => '48.570-000', :state => state); c.save; 
c = City.new(:name => 'Santa Cruz Cabralia', :zip_code => '45.807-000', :state => state); c.save; 
c = City.new(:name => 'Santa Cruz Da Vitoria', :zip_code => '45.725-000', :state => state); c.save; 
c = City.new(:name => 'Santa Ines', :zip_code => '45.320-000', :state => state); c.save; 
c = City.new(:name => 'Santa Luzia', :zip_code => '45.865-000', :state => state); c.save; 
c = City.new(:name => 'Santa Maria Da Vitoria', :zip_code => '47.640-000', :state => state); c.save; 
c = City.new(:name => 'Santa Rita De Cassia', :zip_code => '47.150-000', :state => state); c.save; 
c = City.new(:name => 'Santa Terezinha', :zip_code => '44.590-000', :state => state); c.save; 
c = City.new(:name => 'Santaluz', :zip_code => '48.880-000', :state => state); c.save; 
c = City.new(:name => 'Santana', :zip_code => '47.700-000', :state => state); c.save; 
c = City.new(:name => 'Santanopolis', :zip_code => '44.260-000', :state => state); c.save; 
c = City.new(:name => 'Santiago Do Iguape', :zip_code => '44.310-000', :state => state); c.save; 
c = City.new(:name => 'Santo Amaro', :zip_code => '44.200-000', :state => state); c.save; 
c = City.new(:name => 'Santo Antonio De Barcelona', :zip_code => '45.915-000', :state => state); c.save; 
c = City.new(:name => 'Santo Antonio De Jesus', :zip_code => '44.570-000', :state => state); c.save; 
c = City.new(:name => 'Santo Estevao', :zip_code => '44.190-000', :state => state); c.save; 
c = City.new(:name => 'Santo Inacio', :zip_code => '47.490-000', :state => state); c.save; 
c = City.new(:name => 'Sao Desiderio', :zip_code => '47.820-000', :state => state); c.save; 
c = City.new(:name => 'Sao Domingos', :zip_code => '48.895-000', :state => state); c.save; 
c = City.new(:name => 'Sao Felipe', :zip_code => '44.550-000', :state => state); c.save; 
c = City.new(:name => 'Sao Felix', :zip_code => '44.360-000', :state => state); c.save; 
c = City.new(:name => 'Sao Francisco Do Conde', :zip_code => '43.900-000', :state => state); c.save; 
c = City.new(:name => 'Sao Gabriel', :zip_code => '44.915-000', :state => state); c.save; 
c = City.new(:name => 'Sao Goncalo Dos Campos', :zip_code => '44.330-000', :state => state); c.save; 
c = City.new(:name => 'Sao Joao Da Fortaleza', :zip_code => '48.413-000', :state => state); c.save; 
c = City.new(:name => 'Sao Jose Do Jacuipe', :zip_code => '44.698-000', :state => state); c.save; 
c = City.new(:name => 'Sao Jose Do Prado', :zip_code => '45.958-000', :state => state); c.save; 
c = City.new(:name => 'Sao Jose Do Rio Grande', :zip_code => '47.975-000', :state => state); c.save; 
c = City.new(:name => 'Sao Miguel Das Matas', :zip_code => '44.580-000', :state => state); c.save; 
c = City.new(:name => 'Sao Roque Do Paraguacu', :zip_code => '44.428-000', :state => state); c.save; 
c = City.new(:name => 'Sao Sebastiao Do Passe', :zip_code => '43.850-000', :state => state); c.save; 
c = City.new(:name => 'Sao Timoteo', :zip_code => '46.145-000', :state => state); c.save; 
c = City.new(:name => 'Sapeacu', :zip_code => '44.530-000', :state => state); c.save; 
c = City.new(:name => 'Satiro Dias', :zip_code => '48.485-000', :state => state); c.save; 
c = City.new(:name => 'Saubara', :zip_code => '44.220-000', :state => state); c.save; 
c = City.new(:name => 'Saudavel', :zip_code => '47.570-000', :state => state); c.save; 
c = City.new(:name => 'Saude', :zip_code => '44.740-000', :state => state); c.save; 
c = City.new(:name => 'Seabra', :zip_code => '46.900-000', :state => state); c.save; 
c = City.new(:name => 'Sebastiao Laranjeiras', :zip_code => '46.450-000', :state => state); c.save; 
c = City.new(:name => 'Senhor Do Bonfim', :zip_code => '48.970-000', :state => state); c.save; 
c = City.new(:name => 'Sento Se', :zip_code => '47.350-000', :state => state); c.save; 
c = City.new(:name => 'Sergi', :zip_code => '44.335-000', :state => state); c.save; 
c = City.new(:name => 'Serra Da Canabrava', :zip_code => '48.953-000', :state => state); c.save; 
c = City.new(:name => 'Serra Dourada', :zip_code => '47.740-000', :state => state); c.save; 
c = City.new(:name => 'Guerem', :zip_code => '45.413-000', :state => state); c.save; 
c = City.new(:name => 'Serra Preta', :zip_code => '44.660-000', :state => state); c.save; 
c = City.new(:name => 'Serrinha', :zip_code => '48.700-000', :state => state); c.save; 
c = City.new(:name => 'Serrolandia', :zip_code => '44.710-000', :state => state); c.save; 
c = City.new(:name => 'Simoes Filho', :zip_code => '43.700-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Do Mato', :zip_code => '47.610-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Do Meio', :zip_code => '44.508-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Do Quinto', :zip_code => '48.565-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Grande', :zip_code => '47.825-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Novo', :zip_code => '48.115-000', :state => state); c.save; 
c = City.new(:name => 'Soares', :zip_code => '44.913-000', :state => state); c.save; 
c = City.new(:name => 'Sobradinho', :zip_code => '48.925-000', :state => state); c.save; 
c = City.new(:name => 'Santana Do Sobrado', :zip_code => '47.310-000', :state => state); c.save; 
c = City.new(:name => 'Souto Soares', :zip_code => '46.990-000', :state => state); c.save; 
c = City.new(:name => 'Subauma', :zip_code => '48.190-000', :state => state); c.save; 
c = City.new(:name => 'Sussuarana', :zip_code => '46.605-000', :state => state); c.save; 
c = City.new(:name => 'Tabocas Do Brejo Velho', :zip_code => '47.760-000', :state => state); c.save; 
c = City.new(:name => 'Taboleiro Do Castro', :zip_code => '44.568-000', :state => state); c.save; 
c = City.new(:name => 'Taboquinhas', :zip_code => '45.534-000', :state => state); c.save; 
c = City.new(:name => 'Tagua', :zip_code => '47.930-000', :state => state); c.save; 
c = City.new(:name => 'Tanhacu', :zip_code => '46.600-000', :state => state); c.save; 
c = City.new(:name => 'Tanque Novo', :zip_code => '46.580-000', :state => state); c.save; 
c = City.new(:name => 'Tanquinho', :zip_code => '44.160-000', :state => state); c.save; 
c = City.new(:name => 'Taperoa', :zip_code => '45.430-000', :state => state); c.save; 
c = City.new(:name => 'Tapiraipe', :zip_code => '46.804-000', :state => state); c.save; 
c = City.new(:name => 'Tapirama', :zip_code => '45.543-000', :state => state); c.save; 
c = City.new(:name => 'Tapiramuta', :zip_code => '44.840-000', :state => state); c.save; 
c = City.new(:name => 'Tapiranga', :zip_code => '44.723-000', :state => state); c.save; 
c = City.new(:name => 'Tapuia', :zip_code => '45.449-000', :state => state); c.save; 
c = City.new(:name => 'Taquarinha', :zip_code => '45.935-000', :state => state); c.save; 
c = City.new(:name => 'Taquarendi', :zip_code => '44.748-000', :state => state); c.save; 
c = City.new(:name => 'Tartaruga', :zip_code => '45.318-000', :state => state); c.save; 
c = City.new(:name => 'Tauape', :zip_code => '46.335-000', :state => state); c.save; 
c = City.new(:name => 'Teixeira De Freitas', :zip_code => '45.995-000', :state => state); c.save; 
c = City.new(:name => 'Teodoro Sampaio', :zip_code => '44.280-000', :state => state); c.save; 
c = City.new(:name => 'Teofilandia', :zip_code => '48.770-000', :state => state); c.save; 
c = City.new(:name => 'Teolandia', :zip_code => '45.465-000', :state => state); c.save; 
c = City.new(:name => 'Terra Nova', :zip_code => '44.270-000', :state => state); c.save; 
c = City.new(:name => 'Tijuacu', :zip_code => '48.980-000', :state => state); c.save; 
c = City.new(:name => 'Tiquarucu', :zip_code => '44.140-000', :state => state); c.save; 
c = City.new(:name => 'Itaguacu Da state', :zip_code => '47.440-000', :state => state); c.save; 
c = City.new(:name => 'Tremedal', :zip_code => '45.170-000', :state => state); c.save; 
c = City.new(:name => 'Triunfo Do Sincora', :zip_code => '46.660-000', :state => state); c.save; 
c = City.new(:name => 'Tucano', :zip_code => '48.790-000', :state => state); c.save; 
c = City.new(:name => 'Uaua', :zip_code => '48.950-000', :state => state); c.save; 
c = City.new(:name => 'Ubaira', :zip_code => '45.310-000', :state => state); c.save; 
c = City.new(:name => 'Ubaitaba', :zip_code => '45.545-000', :state => state); c.save; 
c = City.new(:name => 'Ubata', :zip_code => '45.550-000', :state => state); c.save; 
c = City.new(:name => 'Ubiracaba', :zip_code => '46.105-000', :state => state); c.save; 
c = City.new(:name => 'Ubiraita', :zip_code => '46.833-000', :state => state); c.save; 
c = City.new(:name => 'Uibai', :zip_code => '44.950-000', :state => state); c.save; 
c = City.new(:name => 'Umburanas', :zip_code => '44.798-000', :state => state); c.save; 
c = City.new(:name => 'Una', :zip_code => '45.690-000', :state => state); c.save; 
c = City.new(:name => 'Urandi', :zip_code => '46.350-000', :state => state); c.save; 
c = City.new(:name => 'Urucuca', :zip_code => '45.680-000', :state => state); c.save; 
c = City.new(:name => 'Utinga', :zip_code => '46.810-000', :state => state); c.save; 
c = City.new(:name => 'Vale Verde', :zip_code => '45.817-000', :state => state); c.save; 
c = City.new(:name => 'Valenca', :zip_code => '45.400-000', :state => state); c.save; 
c = City.new(:name => 'Valente', :zip_code => '48.890-000', :state => state); c.save; 
c = City.new(:name => 'Varzea Da Roca', :zip_code => '44.635-000', :state => state); c.save; 
c = City.new(:name => 'Varzea Do Caldas', :zip_code => '46.910-000', :state => state); c.save; 
c = City.new(:name => 'Varzea Do Cerco', :zip_code => '44.888-000', :state => state); c.save; 
c = City.new(:name => 'Varzea Do Poco', :zip_code => '44.715-000', :state => state); c.save; 
c = City.new(:name => 'Varzea Nova', :zip_code => '44.690-000', :state => state); c.save; 
c = City.new(:name => 'Varzeas', :zip_code => '47.840-000', :state => state); c.save; 
c = City.new(:name => 'Varzedo', :zip_code => '44.565-000', :state => state); c.save; 
c = City.new(:name => 'Velha Boipeba', :zip_code => '45.426-000', :state => state); c.save; 
c = City.new(:name => 'Ventura', :zip_code => '44.875-000', :state => state); c.save; 
c = City.new(:name => 'Vera Cruz', :zip_code => '44.470-000', :state => state); c.save; 
c = City.new(:name => 'Nova Fatima', :zip_code => '44.642-000', :state => state); c.save; 
c = City.new(:name => 'Vitoria Da Conquista', :zip_code => '45.000-000', :state => state); c.save; 
c = City.new(:name => 'Volta Grande', :zip_code => '44.845-000', :state => state); c.save; 
c = City.new(:name => 'Wagner', :zip_code => '46.970-000', :state => state); c.save; 
c = City.new(:name => 'Wanderley', :zip_code => '47.940-000', :state => state); c.save; 
c = City.new(:name => 'Wenceslau Guimaraes', :zip_code => '45.460-000', :state => state); c.save; 
c = City.new(:name => 'Xique-xique', :zip_code => '47.400-000', :state => state); c.save; 
c = City.new(:name => 'Novo Horizonte', :zip_code => '46.730-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Grande', :zip_code => '44.972-000', :state => state); c.save; 
c = City.new(:name => 'Rio Do Meio', :zip_code => '45.712-000', :state => state); c.save; 
c = City.new(:name => 'Pinhoes', :zip_code => '48.924-000', :state => state); c.save; 
c = City.new(:name => 'Sao Jose Do Colonia', :zip_code => '45.142-000', :state => state); c.save; 
c = City.new(:name => 'Brejo Luiza De Brito', :zip_code => '46.733-000', :state => state); c.save; 
c = City.new(:name => 'Canudos', :zip_code => '44.889-000', :state => state); c.save; 
c = City.new(:name => 'Salobro', :zip_code => '44.892-000', :state => state); c.save; 
c = City.new(:name => 'Mocambo', :zip_code => '46.720-000', :state => state); c.save; 
c = City.new(:name => 'Iuiu', :zip_code => '46.438-000', :state => state); c.save; 
c = City.new(:name => 'Pituba', :zip_code => '47.454-000', :state => state); c.save; 
c = City.new(:name => 'Caimbe', :zip_code => '48.506-000', :state => state); c.save; 
c = City.new(:name => 'Aribice', :zip_code => '48.504-000', :state => state); c.save; 
c = City.new(:name => 'Itati', :zip_code => '45.714-000', :state => state); c.save; 
c = City.new(:name => 'Quixabeira', :zip_code => '44.713-000', :state => state); c.save; 
c = City.new(:name => 'Tamburil', :zip_code => '44.862-000', :state => state); c.save; 
c = City.new(:name => 'Ico', :zip_code => '44.852-000', :state => state); c.save; 
c = City.new(:name => 'Bendego', :zip_code => '48.524-000', :state => state); c.save; 
c = City.new(:name => 'Novo Triunfo', :zip_code => '48.455-000', :state => state); c.save; 
c = City.new(:name => 'Serra Do Ramalho', :zip_code => '47.630-000', :state => state); c.save; 
c = City.new(:name => 'Sao Felix Do Coribe', :zip_code => '47.665-000', :state => state); c.save; 
c = City.new(:name => 'Bonito', :zip_code => '46.820-000', :state => state); c.save; 
c = City.new(:name => 'Nova Brasilia', :zip_code => '45.156-000', :state => state); c.save; 
c = City.new(:name => 'Filanesia', :zip_code => '45.358-000', :state => state); c.save; 
c = City.new(:name => 'Sao Jose Da Vitoria', :zip_code => '45.620-000', :state => state); c.save; 
c = City.new(:name => 'Vereda', :zip_code => '45.955-000', :state => state); c.save; 
c = City.new(:name => 'Barracas', :zip_code => '44.757-000', :state => state); c.save; 
c = City.new(:name => 'Tanquinho Do Poco', :zip_code => '48.994-000', :state => state); c.save; 
c = City.new(:name => 'Sitio Da Barauna', :zip_code => '48.993-000', :state => state); c.save; 
c = City.new(:name => 'Mantiba', :zip_code => '44.117-000', :state => state); c.save; 
c = City.new(:name => 'Matinha', :zip_code => '44.118-000', :state => state); c.save; 
c = City.new(:name => 'Morrinhos', :zip_code => '44.127-000', :state => state); c.save; 
c = City.new(:name => 'Km Sete', :zip_code => '44.133-000', :state => state); c.save; 
c = City.new(:name => 'Limoeiro Do Bom Viver', :zip_code => '44.137-000', :state => state); c.save; 
c = City.new(:name => 'Sao Joao Da Vitoria', :zip_code => '45.111-000', :state => state); c.save; 
c = City.new(:name => 'Abelhas', :zip_code => '45.112-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Jose Luis', :zip_code => '45.113-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa De Melquiades', :zip_code => '45.114-000', :state => state); c.save; 
c = City.new(:name => 'Itaipu', :zip_code => '45.116-000', :state => state); c.save; 
c = City.new(:name => 'Itapirema', :zip_code => '45.117-000', :state => state); c.save; 
c = City.new(:name => 'Caicara', :zip_code => '45.118-000', :state => state); c.save; 
c = City.new(:name => 'Parafuso', :zip_code => '42.849-000', :state => state); c.save; 
c = City.new(:name => 'Itacimirim', :zip_code => '42.823-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Pojuca', :zip_code => '42.825-000', :state => state); c.save; 
c = City.new(:name => 'Guarajuba', :zip_code => '42.827-000', :state => state); c.save; 
c = City.new(:name => 'Canto Do Sol', :zip_code => '42.830-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Jacuipe', :zip_code => '42.833-000', :state => state); c.save; 
c = City.new(:name => 'Arembepe', :zip_code => '42.835-000', :state => state); c.save; 
c = City.new(:name => 'Guagirus', :zip_code => '42.837-000', :state => state); c.save; 
c = City.new(:name => 'Catu De Abrantes', :zip_code => '42.841-000', :state => state); c.save; 
c = City.new(:name => 'Jaua', :zip_code => '42.843-000', :state => state); c.save; 
c = City.new(:name => 'Buris De Abrantes', :zip_code => '42.845-000', :state => state); c.save; 
c = City.new(:name => 'Areias', :zip_code => '42.847-000', :state => state); c.save; 
c = City.new(:name => 'Ilha De Mare', :zip_code => '42.500-000', :state => state); c.save; 
c = City.new(:name => 'Canoao', :zip_code => '44.965-000', :state => state); c.save; 
c = City.new(:name => 'Bate Pe', :zip_code => '45.107-000', :state => state); c.save; 
c = City.new(:name => 'Quaracu', :zip_code => '45.159-000', :state => state); c.save; 
c = City.new(:name => 'Morro De Sao Paulo', :zip_code => '45.428-000', :state => state); c.save; 
c = City.new(:name => 'Colonia', :zip_code => '45.832-000', :state => state); c.save; 
c = City.new(:name => 'Descoberto', :zip_code => '47.695-000', :state => state); c.save; 
c = City.new(:name => 'Mimoso Do Oeste', :zip_code => '47.813-000', :state => state); c.save; 
c = City.new(:name => 'Narandiba', :zip_code => '48.107-000', :state => state); c.save; 
c = City.new(:name => 'Curral Falso', :zip_code => '48.403-000', :state => state); c.save; 
c = City.new(:name => 'Serra Grande', :zip_code => '48.414-000', :state => state); c.save; 
c = City.new(:name => 'Dona Maria', :zip_code => '48.473-000', :state => state); c.save; 
c = City.new(:name => 'Umbuzeiro', :zip_code => '48.474-000', :state => state); c.save; 
c = City.new(:name => 'Buril', :zip_code => '48.483-000', :state => state); c.save; 
c = City.new(:name => 'Barra Do Tarrachil', :zip_code => '48.668-000', :state => state); c.save; 
c = City.new(:name => 'Bandiacu', :zip_code => '48.745-000', :state => state); c.save; 
c = City.new(:name => 'Olhos Dagua Do Seco', :zip_code => '46.715-000', :state => state); c.save; 
c = City.new(:name => 'Angico', :zip_code => '44.633-000', :state => state); c.save; 
c = City.new(:name => 'Alegre', :zip_code => '46.203-000', :state => state); c.save; 
c = City.new(:name => 'Lagoa Grande', :zip_code => '45.158-000', :state => state); c.save; 
c = City.new(:name => 'Pedras Altas Do Mirim', :zip_code => '44.697-000', :state => state); c.save; 
c = City.new(:name => 'Serra Grande', :zip_code => '45.414-000', :state => state); c.save; 
c = City.new(:name => 'Vila Do Cafe', :zip_code => '45.153-000', :state => state); c.save; 
c = City.new(:name => 'Piraja', :zip_code => '45.837-000', :state => state); c.save; 
c = City.new(:name => 'Piragi', :zip_code => '45.837-500', :state => state); c.save; 
c = City.new(:name => 'Ita-azul', :zip_code => '45.838-000', :state => state); c.save; 
c = City.new(:name => 'Nova Alegria', :zip_code => '45.838-500', :state => state); c.save; 
c = City.new(:name => 'Sao Paulinho', :zip_code => '45.839-000', :state => state); c.save; 

