#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

############Organizations########################
Organization.destroy_all
organization = Organization.new
organization.name = 'Toca'
organization.cnpj = '05359933000193'
organization.nickname = 'toca'
organization.save!

############Configuration#########################
configuration = organization.configuration
ProductDisplay.delete_all
configuration.product_display_fields= ProductDisplay.available_fields 
configuration.product_display_fields_in_list= ['name', 'size', 'category' ]
WorkerDisplay.delete_all
configuration.worker_display_fields= WorkerDisplay.available_fields 
configuration.worker_display_fields_in_list= ['name', 'description', 'email' ]
CustomerDisplay.delete_all
configuration.customer_display_fields= CustomerDisplay.available_fields 
configuration.customer_display_fields_in_list= ['name', 'description', 'email' ]
SupplierDisplay.delete_all
configuration.supplier_display_fields= SupplierDisplay.available_fields 
configuration.supplier_display_fields_in_list= ['name', 'description', 'email' ]
ProductCategoryDisplay.delete_all
configuration.product_category_display_fields= ProductCategoryDisplay.available_fields
configuration.product_category_display_fields_in_list= ProductCategoryDisplay.available_fields
CustomerCategoryDisplay.delete_all
configuration.customer_category_display_fields= CustomerCategoryDisplay.available_fields
configuration.customer_category_display_fields_in_list= CustomerCategoryDisplay.available_fields
WorkerCategoryDisplay.delete_all
configuration.worker_category_display_fields= WorkerCategoryDisplay.available_fields
configuration.worker_category_display_fields_in_list= WorkerCategoryDisplay.available_fields
SupplierCategoryDisplay.delete_all
configuration.supplier_category_display_fields= SupplierCategoryDisplay.available_fields
configuration.supplier_category_display_fields_in_list= SupplierCategoryDisplay.available_fields
LedgerCategoryDisplay.delete_all
configuration.ledger_category_display_fields= LedgerCategoryDisplay.available_fields
configuration.ledger_category_display_fields_in_list= LedgerCategoryDisplay.available_fields
LedgerDisplay.delete_all
configuration.ledger_display_fields= LedgerDisplay.available_fields 
configuration.ledger_display_fields_in_list= LedgerDisplay.available_fields
CreditLedgerDisplay.delete_all
configuration.credit_ledger_display_fields= CreditLedgerDisplay.available_fields 
configuration.credit_ledger_display_fields_in_list= CreditLedgerDisplay.available_fields
DebitLedgerDisplay.delete_all
configuration.debit_ledger_display_fields= DebitLedgerDisplay.available_fields 
configuration.debit_ledger_display_fields_in_list= DebitLedgerDisplay.available_fields
BankAccount.delete_all
configuration.bank_account_display_fields= BankAccountDisplay.available_fields
configuration.bank_account_display_fields_in_list= ['bank','agency','variation','account','owner']
DepartmentDisplay.delete_all
configuration.department_display_fields= DepartmentDisplay.available_fields
configuration.department_display_fields_in_list= ['name']
configuration.save!

###########Categories###################################
Category.destroy_all

vestuario = ProductCategory.new(:name => 'vestuário')  
vestuario.organization = organization
vestuario.save!
acessorio = ProductCategory.new(:name => 'acessório')
acessorio.organization = organization
acessorio.save!

fornecedor_vestuario = SupplierCategory.new(:name => 'fornecedor de vestuário')  
fornecedor_vestuario.organization = organization
fornecedor_vestuario.save
fornecedor_acessorio = SupplierCategory.new(:name => 'fornecedor de acessórios')  
fornecedor_acessorio.organization = organization
fornecedor_acessorio.save

consumidor_pessoa = CustomerCategory.new
consumidor_pessoa.name = 'consumidor pessoa física'
consumidor_pessoa.organization = organization
consumidor_pessoa.save
consumidor_empresa = CustomerCategory.new
consumidor_empresa.name = 'consumidor empresa'
consumidor_empresa.organization = organization
consumidor_empresa.save

salesman_category = WorkerCategory.new
salesman_category.name = 'salesman_category'
salesman_category.organization = organization
salesman_category.save
manager_category = WorkerCategory.new
manager_category.name = 'manager_category'
manager_category.organization = organization
manager_category.save

############Products#############################
Product.destroy_all
camisa = Product.new(:name => 'camisa básica', :size => 'p', :color => 'azul', :sell_price => 25.00, :unit => 'letra')
camisa.organization = organization
camisa.category = vestuario
camisa.save!
calca = Product.new(:name => 'calça xadrez', :size => 'p', :color => 'verde', :sell_price => 45.00, :unit => 'letra')
calca.organization = organization
calca.category = vestuario
calca.save!
colar = Product.new(:name => 'colar golfinho', :size => '20', :color => 'preto', :sell_price => 20.00, :unit => 'cm')
colar.organization = organization
colar.category = acessorio
colar.save!
brinco = Product.new(:name => 'brinco madreperola', :size => '4', :color => 'branco', :sell_price => 15.00, :unit => 'cm')
brinco.organization = organization
brinco.category = acessorio
brinco.save!
monitor = Product.new(:name => 'monitor lcd', :size => '15', :color => 'preto', :sell_price => 0.00, :unit => 'polegadas')
monitor.organization = organization
monitor.category = acessorio
monitor.save!

############Images###############################
Image.destroy_all

IMAGE_PATH_DIR = "#{RAILS_ROOT}/script/test_images"

camisa_img = Image.new
camisa_img.description = 'camisa básica azul'
stream = StringIO.new(File.read("#{IMAGE_PATH_DIR}/camisa_basica_azul.jpg"))
def stream.original_filename
  'camisa_basica_azul.jpg'
end
def stream.content_type
  'image/jpg'
end
camisa_img.picture = stream
camisa_img.product = camisa
camisa_img.save!

calca_img = Image.new
calca_img.description = 'calça xadrez'
stream = StringIO.new(File.read("#{IMAGE_PATH_DIR}/calca_xadrez.jpg"))
def stream.original_filename
  'calca_xadrez.jpg'
end
def stream.content_type
  'image/jpg'
end
calca_img.picture = stream
calca_img.product = calca
calca_img.save!

brinco_img = Image.new
brinco_img.description = 'brinco madrepérola'
stream = StringIO.new(File.read("#{IMAGE_PATH_DIR}/brinco_madreperola.jpg"))
def stream.original_filename
  'brinco_madreperola.jpg'
end
def stream.content_type
  'image/jpg'
end
brinco_img.picture = stream
brinco_img.product = brinco
brinco_img.save!

colar_img = Image.new
colar_img.description = 'colar golfinho'
stream = StringIO.new(File.read("#{IMAGE_PATH_DIR}/colar_golfinho.jpg"))
def stream.original_filename
  'colar_golfinho.jpg'
end
def stream.content_type
  'image/jpg'
end
colar_img.picture = stream
colar_img.product = colar
colar_img.save!

monitor_img = Image.new
monitor_img.description = 'monitor lcd'
stream = StringIO.new(File.read("#{IMAGE_PATH_DIR}/monitor_lcd.jpg"))
def stream.original_filename
  'monitor_lcd.jpg'
end
def stream.content_type
  'image/jpg'
end
monitor_img.picture = stream
monitor_img.product = monitor
monitor_img.save!

############Suppliers#############################
Supplier.destroy_all
hering = Supplier.create!(:name => 'Hering', :cnpj => '58178734000145', :organization => organization, :address => 'R Hermann Hering 1790 CEP: 89010900 Cidade: Blumenau UF: SC', :description => 'fornecedor de roupas', :email => 'contato@hering.com', :category => fornecedor_vestuario)
mundo_prata = Supplier.create!(:name => 'Mundo das Pratas', :cpf => '39377825679', :organization => organization, :address => 'Rua: Fonte do Boi, 215 - Rio Vermelho', :birthday => '1980-05-12', :description => 'fornecedor de pratas', :email => 'contato@mundo_das_pratas.com', :category => fornecedor_acessorio)

############Product Suppliers#####################
camisa.add_suppliers(hering)
calca.add_suppliers(hering)
colar.add_suppliers(mundo_prata)
brinco.add_suppliers(mundo_prata)

############Stock Entries#########################
StockEntry.destroy_all
camisa_entrada = StockIn.create!(:supplier => hering, :ammount => 50, :price => '15.00', :purpose => 'sell', :date => '2007-07-01', :payment_status => true, :product => camisa)
calca_entrada = StockIn.create!(:supplier => hering, :ammount => 50, :price => '30.00', :purpose => 'sell', :date => '2007-07-01', :payment_status => true, :product => calca)

############People################################
Person.destroy_all
gerente = User.create!("administrator"=>false, "login"=>"quentin", "email"=>"quentin@example.com", :password => 'test', :password_confirmation => 'test')
another_gerente = User.create!("password"=>"juca", "password_confirmation" => 'juca', "administrator"=>false, "login"=>"juca", "email"=>"juca@example.com")
test_user = User.create!("administrator"=>false, "login"=>"test", "email"=>"test@example.com", :password => 'test', :password_confirmation => 'test')
admin = User.create!("administrator"=>true, "login"=>"admin", "email"=>"admin@example.com", :password => 'admin', :password_confirmation => 'admin' )

############User Profile##########################
Profile.destroy_all
perfil_organization = Profile.new
perfil_organization.organization = organization
perfil_organization.user = gerente
perfil_organization.template = 'organization_management'
perfil_organization.save!

perfil_admin = Profile.new
perfil_admin.user = admin
perfil_admin.template = 'administration'
perfil_admin.save!

############Customers#############################
Customer.destroy_all
cliente_one = Customer.create!(:name => 'João da Silva', :email => 'joao@colibre.coop.br', :birthday => '1984-08-15', :address => 'Rua Pará, nº 221, Pituba', :cpf => '74676743920', :organization => organization, :category => consumidor_empresa)
cliente_two = Customer.create!(:name => 'Alice Soares', :email => 'livia@localhost', :birthday => '1970-10-22', :address => 'Rua João das Botas, nº 15, Canela', :cpf => '93791122894', :organization => organization, :category => consumidor_pessoa)
cliente_one = Customer.create!(:name => 'Lívia Barreiros', :email => 'livinhaba@gmail.com', :birthday => '1982-03-05', :address => 'Rua Prado Valadares, nº 19, apt202, Nazaré', :cpf => '01652747516', :organization => organization, :category => consumidor_pessoa)

############Contacts###############################
Contact.destroy_all

############Contact Positions######################

############Workers################################
Worker.destroy_all
vendedor = Worker.create!(:name => 'José Fernandes', :cpf => '63358421813', :address => 'Rua do Timbó, nº 45, Itaigara', :birthday => '1975-06-14', :category => salesman_category, :organization => organization, :email => 'jose@toca.com')
gerente = Worker.create!(:name => 'Carla Alves', :cpf => '53170430424', :address => 'Alameda das Pintagueiras, nº 37, Caminho das Árvores', :birthday => '1979-07-18', :category => manager_category, :organization => organization, :email => 'carla@toca.com')

############Payments################################
#TODO see it's usefull
#Payment.destroy_all

############Sales###################################
Sale.destroy_all

############Sale Items##############################
SaleItem.destroy_all

############Mass Mail###############################
MassMail.destroy_all
mail_one = MassMail.create!(:subject => 'Festa de Inauguração da Toca!', :body => 'Olá, a Toca o convida para a sua festa de inauguração. Não perca!', :organization => organization)
mail_one = MassMail.create!(:subject => 'Conheça o site da Toca', :body => 'Olá, o site da Toca está disponível em http://www.consumidorsustentavel.com.br/http://www.consumidorsustentavel.com.br/.', :organization => organization)

############Departments###############################
Department.destroy_all
marketing_department = Department.create!(:name => 'Marketing', :organization => organization)
departamento_vendas = Department.create!(:name => 'Vendas', :organization => organization)

############Document######################
Document.destroy_all
proposal = Document.create!(:name => 'Estruturação do espaço de eventos', :is_model => true, :organization => organization, :body => 'Parceria com a Colivre para estruturação do espaço para realização de cursos de sofware livre.', :departments => [marketing_department])

###########Document Section################
DocumentSection.destroy_all
section_one = DocumentSection.create!(:name => 'máquinas', :document => proposal)

############Document Items#################
DocumentItem.destroy_all
item_one = DocumentItem.create!(:document_section => section_one, :quantity => '10', :unitary_value => 400.00,:product => monitor)

########### Bank ###################
Bank.delete_all
bank = Bank.create!(:code => '001', :name => 'Banco do Brasil S.A. ', :site => 'www.bb.com.br')
 

########### Bank Account ###################
BankAccount.delete_all
account = BankAccount.new(:agency => '3352-3', :account => '23456-3')
account.bank = bank
account.owner = organization
account.is_default = true
account.save!
saving_account = BankAccount.new(:agency => '3352-3', :account => '23456-3', :variation => 1)
saving_account.bank = bank
saving_account.owner = organization
saving_account.save!

########### Ledger Category ###################
LedgerCategory.delete_all
ledger_category_expense = LedgerCategory.create!(:name => 'Limpeza', :organization => organization, :type_of => LedgerCategory::TYPE_OF_EXPENSE)
ledger_category_income = LedgerCategory.create!(:name => 'Venda Produto', :organization => organization, :type_of => LedgerCategory::TYPE_OF_INCOME)

#############################
# Period
# ###########################

Periodicity.delete_all
Periodicity.create!(:name => 'Mensal', :number_of_days => 30, :organization => organization)
Periodicity.create!(:name => 'Quinzenal', :number_of_days => 15, :organization => organization)

#############################
# Ledger
# ###########################

Ledger.delete_all
DebitLedger.create!(:category => ledger_category_expense, :value => 2.3, :bank_account => account, :date => Date.today)
CreditLedger.create!(:category => ledger_category_income, :value => 222.50, :bank_account => account, :date => Date.today)

