#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

############Organizations########################
Organization.destroy_all
organization = Organization.create!(:name => 'Toca', :cnpj => '05359933000193', :nickname => 'toca')
configuration = organization.configuration
configuration.full_product = Product.available_fields
configuration.lite_product = ['name', 'category_id','sell_price']
configuration.full_customer = Customer.available_fields
configuration.lite_customer = ['name', 'category_id','address']
configuration.save!

###########Categories###################################
Category.destroy_all

vestuario = ProductCategory.new(:name => 'vestuário')  
vestuario.organization = organization
vestuario.save!
acessorio = ProductCategory.new(:name => 'acessório')
acessorio.organization = organization
acessorio.save!

fornecedor_vestuario = SupplierCategory.new(:name => 'fornecedor de vestuário')  
fornecedor_vestuario.organization = organization
fornecedor_vestuario.save
fornecedor_acessorio = SupplierCategory.new(:name => 'fornecedor de acessórios')  
fornecedor_acessorio.organization = organization
fornecedor_acessorio.save

consumidor_pessoa = CustomerCategory.new
consumidor_pessoa.name = 'consumidor pessoa física'
consumidor_pessoa.organization = organization
consumidor_pessoa.save
consumidor_empresa = CustomerCategory.new
consumidor_empresa.name = 'consumidor empresa'
consumidor_empresa.organization = organization
consumidor_empresa.save

vendedor = WorkerCategory.new
vendedor.name = 'vendedor'
vendedor.organization = organization
vendedor.save
gerente = WorkerCategory.new
gerente.name = 'gerente'
gerente.organization = organization
gerente.save

############Images###############################
#Image.destroy_all
#camisa_img = Image.new
#camisa_img.description = 'camisa básica azul'
#stream = StringIO.new(File.read('public/test_images/camisa_basica_azul.jpg'))

#    def stream.original_filename
#      'camisa_basica_azul.jpg'
#    end
    
#    def stream.content_type
#      'image/jpg'
#    end

#camisa_img.picture = stream
#camisa_img.save!

############Products#############################
Product.destroy_all
camisa = Product.new(:name => 'camisa básica', :size => 'p', :color => 'azul', :sell_price => 25.00, :unit => 'letra')
camisa.organization = organization
camisa.category = vestuario
camisa.save!
calca = Product.new(:name => 'calça xadrez', :size => 'p', :color => 'verde', :sell_price => 45.00, :unit => 'letra')
calca.organization = organization
calca.category = vestuario
calca.save!
colar = Product.new(:name => 'colar golfinho', :size => '20', :color => 'preto', :sell_price => 20.00, :unit => 'cm')
colar.organization = organization
colar.category = acessorio
colar.save!
brinco = Product.new(:name => 'brinco madreperola', :size => '4', :color => 'branco', :sell_price => 15.00, :unit => 'cm')
brinco.organization = organization
brinco.category = acessorio
brinco.save!
monitor = Product.new(:name => 'monitor lcd', :size => '15', :color => 'preto', :sell_price => 0.00, :unit => 'polegadas')
monitor.organization = organization
monitor.category = acessorio
monitor.save!

#############Images##############################
#Image.destroy_all
#camisa_img = Image.create!(:description => 'camisa básica azul', :picture => 'camisa_basica_azul.jpg', :product_id => 1)
#calca_img = Image.create!(:description => 'calca xadrez verde', :picture => 'calca_xadrez.jpg', :product_id => 2)
#colar_img = Image.create!(:description => 'colar golfinho', :picture => 'colar_golfinho.jpg', :product_id => 3)
#brinco_img = Image.create!(:description => 'brinco madreperola', :picture => 'brinco_madreperola.jpg', :product_id => 4)

############Suppliers#############################
Supplier.destroy_all
hering = Supplier.create!(:name => 'Hering', :cnpj => '58178734000145', :organization_id => 1, :address => 'R Hermann Hering 1790 CEP: 89010900 Cidade: Blumenau UF: SC', :description => 'fornecedor de roupas', :email => 'contato@hering.com', :category_id => 3)
mundo_prata = Supplier.create!(:name => 'Mundo das Pratas', :cpf => '39377825679', :organization_id => 1, :address => 'Rua: Fonte do Boi, 215 - Rio Vermelho', :birthday => '1980-05-12', :description => 'fornecedor de pratas', :email => 'contato@mundo_das_pratas.com', :category_id => 4)

############Product Suppliers#####################
camisa.add_suppliers(hering)
calca.add_suppliers(hering)
colar.add_suppliers(mundo_prata)
brinco.add_suppliers(mundo_prata)

############Stock Entries#########################
StockEntry.destroy_all
camisa_entrada = StockIn.create!(:supplier_id => '1', :ammount => 50, :price => '15.00', :purpose => 'sell', :date => '2007-07-01', :payment_status => true, :product_id => 1)
calca_entrada = StockIn.create!(:supplier_id => '1', :ammount => 50, :price => '30.00', :purpose => 'sell', :date => '2007-07-01', :payment_status => true, :product_id => 2)

############People################################
Person.destroy_all
gerente = User.create!("salt"=>"7e3041ebc2fc05a40c60028e2c4901a81035d3cd", "updated_at"=>nil, "crypted_password"=>"00742970dc9e6319f8019fd54864d3ea740f04b1", "type"=>"User", "remember_token_expires_at"=>nil, "id"=>"1", "administrator"=>false, "remember_token"=>nil, "login"=>"quentin", "email"=>"quentin@example.com", "created_at"=>"2007-07-14 18:03:29")
admin = User.create!("salt"=>"7e3041ebc2fc05a40c60028e2c4901a81035d3cd", "updated_at"=>nil, "crypted_password"=>"00742970dc9e6319f8019fd54864d3ea740f04b1", "type"=>"User", "remember_token_expires_at"=>nil, "id"=>"1", "administrator"=>true, "remember_token"=>nil, "login"=>"admin", "email"=>"admin@example.com", "created_at"=>"2007-07-14 18:03:29")

############User Profile##########################
Profile.destroy_all
perfil_organization = Profile.new
perfil_organization.organization = organization
perfil_organization.user = gerente
perfil_organization.template = 'organization_management'
perfil_organization.save!

perfil_admin = Profile.new
perfil_admin.user = admin
perfil_admin.template = 'administration'
perfil_admin.save!

############Customers#############################
Customer.destroy_all
cliente_one = Customer.create!(:name => 'João da Silva', :email => 'joao@colibre.coop.br', :birthday => '1984-08-15', :address => 'Rua Pará, nº 221, Pituba', :cpf => '74676743920', :organization_id => 1, :category_id => 6)
cliente_two = Customer.create!(:name => 'Alice Soares', :email => 'livia@localhost', :birthday => '1970-10-22', :address => 'Rua João das Botas, nº 15, Canela', :cpf => '93791122894', :organization_id => 1, :category_id => 5)
cliente_one = Customer.create!(:name => 'Lívia Barreiros', :email => 'livinhaba@gmail.com', :birthday => '1982-03-05', :address => 'Rua Prado Valadares, nº 19, apt202, Nazaré', :cpf => '01652747516', :organization_id => 1, :category_id => 5)

############Contacts###############################
Contact.destroy_all

############Contact Positions######################

############Workers################################
Worker.destroy_all
vendedor = Worker.create!(:name => 'José Fernandes', :cpf => '63358421813', :address => 'Rua do Timbó, nº 45, Itaigara', :birthday => '1975-06-14', :category_id => 7, :organization_id => 1, :email => 'jose@toca.com')
gerente = Worker.create!(:name => 'Carla Alves', :cpf => '53170430424', :address => 'Alameda das Pintagueiras, nº 37, Caminho das Árvores', :birthday => '1979-07-18', :category_id => 8, :organization_id => 1, :email => 'carla@toca.com')

############Payments################################
Payment.destroy_all

############Sales###################################
Sale.destroy_all

############Sale Items##############################
SaleItem.destroy_all

############Mass Mail###############################
MassMail.destroy_all
mail_one = MassMail.create!(:subject => 'Festa de Inauguração da Toca!', :body => 'Olá, a Toca o convida para a sua festa de inauguração. Não perca!', :organization_id => 1)
mail_one = MassMail.create!(:subject => 'Conheça o site da Toca', :body => 'Olá, o site da Toca está disponível em http://www.consumidorsustentavel.com.br/http://www.consumidorsustentavel.com.br/.', :organization_id => 1)

############Historicals#############################
Historical.destroy_all

############Specification###########################
Specification.destroy_all

############Departments###############################
Department.destroy_all
departamento_marketing = Department.create!(:name => 'Marketing', :organization_id => 1)
departamento_vendas = Department.create!(:name => 'Vendas', :organization_id => 1)

############Document######################
Document.destroy_all
proposta_colivre = Document.create!(:name => 'Estruturação do espaço de eventos', :is_model => true, :organization_id => 1, :body => 'Parceria com a Colivre para estruturação do espaço para realização de cursos de sofware livre.', :department_ids => [1])

############Document Items#################
DocumentItem.destroy_all
item_one = DocumentItem.create!(:document_section_id => 1, :quantity => '10', :unitary_value => 400.00,:product_id => 5)

###########Document Section################
DocumentSection.destroy_all
section_one = DocumentSection.create!(:name => 'máquinas', :document_id => 1)

########### Bank ###################
Bank.delete_all
bank = Bank.create!(:code => '001', :name => 'Banco do Brasil S.A. ', :site => 'www.bb.com.br')
 

########### Bank Account ###################
BankAccount.delete_all
account = BankAccount.new(:agency => '3352-3', :account => '23456-3')
account.bank = bank
account.owner = organization
account.is_default = true
account.save!
saving_account = BankAccount.new(:agency => '3352-3', :account => '23456-3', :variation => 1)
saving_account.bank = bank
saving_account.owner = organization
saving_account.save!

########### Ledger Category ###################
LedgerCategory.delete_all
ledger_category_expense = LedgerCategory.create!(:name => 'Limpeza', :organization => organization, :type_of => LedgerCategory::TYPE_OF_EXPENSE)
ledger_category_income = LedgerCategory.create!(:name => 'Venda Produto', :organization => organization, :type_of => LedgerCategory::TYPE_OF_INCOME)

#############################
# Period
# ###########################

Periodicity.delete_all
Periodicity.create!(:name => 'Mensal', :number_of_days => 30, :organization => organization)
Periodicity.create!(:name => 'Quinzenal', :number_of_days => 15, :organization => organization)

#############################
# Ledger
# ###########################

Ledger.delete_all
DebitLedger.create!(:category => ledger_category_expense, :value => 2.3, :bank_account => account, :date => Date.today)
CreditLedger.create!(:category => ledger_category_income, :value => 222.50, :bank_account => account, :date => Date.today)

