#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'
system "ruby #{RAILS_ROOT}/script/brazilian_territories/acre_cities.rb"
system "ruby #{RAILS_ROOT}/script/brazilian_territories/alagoas_cities.rb"
#system "ruby #{RAILS_ROOT}/script/brazilian_territories/amapa_cities.rb"
#system "ruby #{RAILS_ROOT}/script/brazilian_territories/amazonas_cities.rb"
