#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

system "rm #{RAILS_ROOT}/tmp/*.db"
system "rake db:migrate VERSION=0"
system "rake db:migrate"
system "rake db:test:prepare"
system "ruby #{RAILS_ROOT}/script/populate_clothes_store"
system "ruby #{RAILS_ROOT}/script/populate_store"
#system "ruby #{RAILS_ROOT}/script/brazil_bank_list"
