class Color < ActiveRecord::Base

  COLOR = {
#     nil =>  t(:n/a),
#    '#F0F8FF' =>  t(:alice_blue),
#    '#FAEBD7' =>  t(:antique_white),
#    '#00FFFF' =>  t(:aqua),
#    '#7FFFD4' =>  t(:aquamarine),
#    '#F0FFFF' =>  t(:azure),
#    '#F5F5DC' =>  t(:beige),
#    '#FFE4C4' =>  t(:bisque),
#    '#000000' =>  t(:black),
#    '#FFEBCD' =>  t(:blanched_almond),
#    '#0000FF' =>  t(:blue),
#    '#8A2BE2' =>  t(:blue_violet),
#    '#A52A2A' =>  t(:brown),
#    '#DEB887' =>  t(:burly_wood),
#    '#5F9EA0' =>  t(:cadet_blue),
#    '#7FFF00' =>  t(:chartreuse),
#    '#D2691E' =>  t(:chocolate),
#    '#FF7F50' =>  t(:coral),
#    '#6495ED' =>  t(:cornflower_blue),
#    '#FFF8DC' =>  t(:cornsilk),
#    '#DC143C' =>  t(:crimson),
#    '#00FFFF' =>  t(:cyan),
#    '#00008B' =>  t(:dark_blue),
#    '#008B8B' =>  t(:dark_cyan),
#    '#B8860B' =>  t(:dark_golden_rod),
#    '#A9A9A9' =>  t(:dark_gray),
#    '#A9A9A9' =>  t(:dark_grey),
#    '#006400' =>  t(:dark_green),
#    '#BDB76B' =>  t(:dark_khaki),
#    '#8B008B' =>  t(:dark_magenta),
#    '#556B2F' =>  t(:dark_olive_green),
#    '#FF8C00' =>  t(:darkorange),
#    '#9932CC' =>  t(:dark_orchid),
#    '#8B0000' =>  t(:dark_red),
#    '#E9967A' =>  t(:dark_salmon),
#    '#8FBC8F' =>  t(:dark_sea_green),
#    '#483D8B' =>  t(:dark_slate_blue),
#    '#2F4F4F' =>  t(:dark_slate_gray),
#    '#2F4F4F' =>  t(:dark_slate_grey),
#    '#00CED1' =>  t(:dark_turquoise),
#    '#9400D3' =>  t(:dark_violet),
#    '#FF1493' =>  t(:deep_pink),
#    '#00BFFF' =>  t(:deep_sky_blue),
#    '#696969' =>  t(:dim_gray),
#    '#696969' =>  t(:dim_grey),
#    '#1E90FF' =>  t(:dodger_blue),
#    '#B22222' =>  t(:fire_brick),
#    '#FFFAF0' =>  t(:floral_white),
#    '#228B22' =>  t(:forest_green),
#    '#FF00FF' =>  t(:fuchsia),
#    '#DCDCDC' =>  t(:gainsboro),
#    '#F8F8FF' =>  t(:ghost_white),
#    '#FFD700' =>  t(:gold),
#    '#DAA520' =>  t(:golden_rod),
#    '#808080' =>  t(:gray),
#    '#808080' =>  t(:grey),
#    '#008000' =>  t(:green),
#    '#ADFF2F' =>  t(:green_yellow),
#    '#F0FFF0' =>  t(:honey_dew),
#    '#FF69B4' =>  t(:hot_pink),
#    '#CD5C5C' =>  t(:indian_red),
#    '#4B0082' =>  t(:indigo),
#    '#FFFFF0' =>  t(:ivory),
#    '#F0E68C' =>  t(:khaki),
#    '#E6E6FA' =>  t(:lavender),
#    '#FFF0F5' =>  t(:lavender_blush),
#    '#7CFC00' =>  t(:lawn_green),
#    '#FFFACD' =>  t(:lemon_chiffon),
#    '#ADD8E6' =>  t(:light_blue),
#    '#F08080' =>  t(:light_coral),
#    '#E0FFFF' =>  t(:light_cyan),
#    '#FAFAD2' =>  t(:light_golden_rod_yellow),
#    '#D3D3D3' =>  t(:light_gray),
#    '#D3D3D3' =>  t(:light_grey),
#    '#90EE90' =>  t(:light_green),
#    '#FFB6C1' =>  t(:light_pink),
#    '#FFA07A' =>  t(:light_salmon),
#    '#20B2AA' =>  t(:light_sea_green),
#    '#87CEFA' =>  t(:light_sky_blue),
#    '#778899' =>  t(:light_slate_gray),
#    '#778899' =>  t(:light_slate_grey),
#    '#B0C4DE' =>  t(:light_steel_blue),
#    '#FFFFE0' =>  t(:light_yellow),
#    '#00FF00' =>  t(:lime),
#    '#32CD32' =>  t(:lime_green),
#    '#FAF0E6' =>  t(:linen),
#    '#FF00FF' =>  t(:magenta),
#    '#800000' =>  t(:maroon),
#    '#66CDAA' =>  t(:medium_aqua_marine),
#    '#0000CD' =>  t(:medium_blue),
#    '#BA55D3' =>  t(:medium_orchid),
#    '#9370D8' =>  t(:medium_purple),
#    '#3CB371' =>  t(:medium_sea_green),
#    '#7B68EE' =>  t(:medium_slate_blue),
#    '#00FA9A' =>  t(:medium_spring_green),
#    '#48D1CC' =>  t(:medium_turquoise),
#    '#C71585' =>  t(:medium_violet_red),
#    '#191970' =>  t(:midnight_blue),
#    '#F5FFFA' =>  t(:mint_cream),
#    '#FFE4E1' =>  t(:misty_rose),
#    '#FFE4B5' =>  t(:moccasin),
#    '#FFDEAD' =>  t(:navajo_white),
#    '#000080' =>  t(:navy),
#    '#FDF5E6' =>  t(:old_lace),
#    '#808000' =>  t(:olive),
#    '#6B8E23' =>  t(:olive_drab),
#    '#FFA500' =>  t(:orange),
#    '#FF4500' =>  t(:orange_red),
#    '#DA70D6' =>  t(:orchid),
#    '#EEE8AA' =>  t(:pale_golden_rod),
#    '#98FB98' =>  t(:pale_green),
#    '#AFEEEE' =>  t(:pale_turquoise),
#    '#D87093' =>  t(:pale_violet_red),
#    '#FFEFD5' =>  t(:papaya_whip),
#    '#FFDAB9' =>  t(:peach_puff),
#    '#CD853F' =>  t(:peru),
#    '#FFC0CB' =>  t(:pink),
#    '#DDA0DD' =>  t(:plum),
#    '#B0E0E6' =>  t(:powder_blue),
#    '#800080' =>  t(:purple),
#    '#FF0000' =>  t(:red),
#    '#BC8F8F' =>  t(:rosy_brown),
#    '#4169E1' =>  t(:royal_blue),
#    '#8B4513' =>  t(:saddle_brown),
#    '#FA8072' =>  t(:salmon),
#    '#F4A460' =>  t(:sandy_brown),
#    '#2E8B57' =>  t(:sea_green),
#    '#FFF5EE' =>  t(:sea_shell),
#    '#A0522D' =>  t(:sienna),
#    '#C0C0C0' =>  t(:silver),
#    '#87CEEB' =>  t(:sky_blue),
#    '#6A5ACD' =>  t(:slate_blue),
#    '#708090' =>  t(:slate_gray),
#    '#708090' =>  t(:slate_grey),
#    '#FFFAFA' =>  t(:snow),
#    '#00FF7F' =>  t(:spring_green),
#    '#4682B4' =>  t(:steel_blue),
#    '#D2B48C' =>  t(:tan),
#    '#008080' =>  t(:teal),
#    '#D8BFD8' =>  t(:thistle),
#    '#FF6347' =>  t(:tomato),
#    '#40E0D0' =>  t(:turquoise),
#    '#EE82EE' =>  t(:violet),
#    '#F5DEB3' =>  t(:wheat),
#    '#FFFFFF' =>  t(:white),
#    '#F5F5F5' =>  t(:white_smoke),
#    '#FFFF00' =>  t(:yellow),
#    '#9ACD32' =>  t(:yellow_green),
  }

  def self.find(*args)
    size_objects = Array.new

    case args.first
      when :first then ColorObject.new('#FFFFFF', COLOR['#FFFFFF'])
      when :all then 
        COLOR.each do |k,v|
          size_objects.push(ColorObject.new(k, v))
        end
        size_objects
      else ColorObject.new(args.first, COLOR[args.first])
    end
  end

end

class ColorObject

  attr_accessor :name, :id

  def initialize(id, name)
    self.id = id
    self.name = name
  end

end

